// ladder_dp_n.v -- ladder_dp.v with NCH independent filter channels (state sets) on one
// datapath, bit-exact against model/fixed.py on every channel (tb_ladder_n.v).
//
// The Python model (LadderFx: 24-bit state with 20 fraction bits, Q0.16
// coefficients, a 2^n-entry edge-sampled tanh table read with linear
// interpolation, half-sample feedback delay, 2x oversampling) is the
// specification. verify_ladder.py / tb_ladder.v compare this module against it
// sample for sample with no tolerance, and the negative controls at the
// INJECT_BUG_LADDER_* defines prove that comparison can fail. Nothing below is
// a numeric choice the model did not already make.
//
// Structure: ONE multiplier and ONE tanh unit, sequenced. Per output sample,
// in the order the model computes them:
//
//   xg = (x * gain) >> 11                                  1 multiply, once
//   per oversample pass (x2):
//     fb  = (d1 + d2) >> 1;  kfb = (k * fb) >> 14          1 multiply
//     u   = sat24(xg - kfb);  w0 = tanh(u)                 1 multiply (interp)
//     for s in 0..3:
//       y_s = sat24(y_s + ((g * (w_{s-1} - w_s)) >> 11))   1 multiply
//       w_s = tanh(y_s)                                    1 multiply (interp)
//     d2 = d1; d1 = y_3
//   y_out = satOW(((y_3 >> 5) * ogain) >> 16)              1 multiply
//
// 22 multiplies, one per clock, through one 24x20 multiplier: 24 clocks per
// sample measured by tb_cycles.v. The tanh unit is a (2^n + 1)-word ROM read
// at bin edges plus a linear interpolation whose multiply is the shared one,
// so the table costs no second multiplier. That interpolation is what makes a
// 16-entry table as good as 256 (model/test_fixed.py); the earlier sketch had
// the small table but not the interpolation, and read the ROM out of range.
//
// tanh(v), v the 24-bit state:  a = |v|;  clamp to rom[2^n] if a >= 4.0;
//   else idx = a[21:22-n], frac = a[21-n:0],
//        r = rom[idx] + ((rom[idx+1] - rom[idx]) * frac) >> (22-n);
//   result = -r if v < 0.  rom[2^n] is the model's guard word, tanh(4)*32767
//   = 32745 -- and the CLAMP above 4.0 returns that same word, so the table
//   and the clamp cannot drift apart (they did: both were 32767 to rev 9).
//
// Formats, all the model's:
//   x_in   Q1.15 signed          y_out  Q(OW-15).15 signed, saturated to OW bits (19: the voice's Q4.15)
//   state  Q4.20 signed, 24 bit  in units of 2*Vt, so the tanh argument IS the state
//   g      Q0.16 unsigned        cutoff; 61,659 at the 0.45*fs clamp -- bit 15 is data
//   k      Q3.14 unsigned        4*res; 17 bits because res = 1.0 is exactly 65,536
//   gain   Q4.16 unsigned        drive * vpu / 2Vt = 2.6 * drive
//   ogain  Q4.16 unsigned        2Vt / vpu * (1 + 2*res)
// x_in is consumed in the clock sample_valid is accepted; g, k, gain and ogain
// must be held while busy. sample_valid is ignored while busy.
`default_nettype none
module ladder_dp_n #(
    parameter NCH        = 1,            // independent filter channels sharing this datapath
    parameter CHW        = (NCH > 1) ? $clog2(NCH) : 1,
    parameter SW         = 24,           // state width          (LadderFx state_bits)
    parameter SQ         = 20,           // state fraction bits  (LadderFx state_q)
    parameter TANH_LOG2N = 4,            // 2^n table entries over [0, 4)
    parameter ROM_FILE   = "tanh16.hex", // 2^n + 1 words, generated by tanh_rom.py
    parameter OW         = 19            // output width (LadderFx out_bits): 19 = the voice's Q4.15 (DR 0005), 16 = rev 1
)(
    input  wire               clk,
    input  wire               rst_n,
    input  wire               sample_valid,
    input  wire               os2x,        // 1: two updates per sample; 0: one high-rate update
    input  wire [CHW-1:0]     ch,           // channel this sample belongs to, sampled with sample_valid
    input  wire signed [16:0] x_in,         // Q1.15-scaled; high-rate reconstruction may exceed int16
    input  wire        [15:0] g,
    input  wire        [16:0] k,
    input  wire        [19:0] gain,
    input  wire        [19:0] ogain,
    output reg  signed [OW-1:0] y_out,
    output reg                y_valid,
    output reg  [CHW-1:0]     y_ch
);
    localparam TQ    = SQ - 15;                  // Q1.15 -> state: shift left by this
    localparam FRACW = SQ + 2 - TANH_LOG2N;      // interpolation fraction bits
    localparam N     = 1 << TANH_LOG2N;
    localparam PW    = SW + 21;                  // product width, 24 x (1+20)
    localparam AW    = SW + 4;                   // pre-saturation arithmetic width: every
                                                 // intermediate below is under 2^27 in magnitude

    // ---- tanh table: the model's tbl[0..N-1] plus the guard word ------------
    reg signed [15:0] rom [0:N];
    initial $readmemh(ROM_FILE, rom);

    // ---- state ---------------------------------------------------------------
    reg signed [SW-1:0] y [0:4*NCH-1];          // per channel: 4 stages
    reg signed [15:0]   w [0:4*NCH-1];          // tanh(y_s), Q1.15, eq (17)'s reuse
    reg signed [SW-1:0] d1 [0:NCH-1];            // last two y_3 for the half-sample delay
    reg signed [SW-1:0] d2 [0:NCH-1];
    reg        [CHW-1:0] chr;                    // channel of the sample in flight
    wire       [CHW-1:0] chsel = (NCH == 1) ? {CHW{1'b0}} : ch;
    reg signed [SW:0]   xg;                      // (x * gain) >> 11, 25 bits
    reg [3:0] step;                              // 0 idle, 1..12 below
    reg       os;                                // oversample pass
    reg       os2r;                              // per-sample two-update mode
    reg       busy;

    // ---- the one multiplier: 24-bit signed x 20-bit unsigned ---------------
    reg  signed [SW-1:0] mul_a;
    reg         [19:0]   mul_b;
    wire signed [PW-1:0] mul_r = mul_a * $signed({1'b0, mul_b});

    // ---- saturation, the model's sat(v, bits) -------------------------------
    localparam signed [AW-1:0] SMAX = (1 << (SW - 1)) - 1;
    localparam signed [AW-1:0] SMIN = -(1 << (SW - 1));
    function signed [SW-1:0] sat_s(input signed [AW-1:0] v);
        sat_s = (v > SMAX) ? SMAX[SW-1:0] : (v < SMIN) ? SMIN[SW-1:0] : v[SW-1:0];
    endfunction
    localparam signed [AW-1:0] OMAX = (1 << (OW - 1)) - 1;
    localparam signed [AW-1:0] OMIN = -(1 << (OW - 1));
    function signed [OW-1:0] sat_o(input signed [AW-1:0] v);
        sat_o = (v > OMAX) ? OMAX[OW-1:0] : (v < OMIN) ? OMIN[OW-1:0] : v[OW-1:0];
    endfunction

    // ---- feedback: half-sample delay as the average of the last two outputs -
    // 25-bit sums: both terms can sit near a rail at once.
    wire [1:0]           s      = (step - 4'd3) >> 1;      // stage, steps 3..10
    wire [1:0]           sm1    = s - 2'd1;
    wire [CHW+1:0]       ys     = {chr, s};                // y/w index of stage s
    wire [CHW+1:0]       ysm1   = {chr, sm1};
    wire [CHW+1:0]       y3i    = {chr, 2'd3};
`ifdef INJECT_BUG_LADDER_CH_BLEED
    wire [CHW-1:0] dch = {CHW{1'b0}};            // NEGATIVE CONTROL: the half-sample delay
`else                                            //   line shared by every channel -- the
    wire [CHW-1:0] dch = chr;                    //   classic "forgot to index by channel"
`endif
    wire signed [SW:0] dsum0 = d1[dch] + d2[dch];          // pass 0
    wire signed [SW:0] dsum1 = y[y3i] + d1[dch];           // pass 1, before d1/d2 shift
`ifdef INJECT_BUG_LADDER_FB
    wire signed [SW-1:0] fb0 = d1[dch];          // NEGATIVE CONTROL: unit delay, no averaging
    wire signed [SW-1:0] fb1 = y[y3i];
`else
    wire signed [SW-1:0] fb0 = dsum0 >>> 1;
    wire signed [SW-1:0] fb1 = dsum1 >>> 1;
`endif

    // ---- what the product means this cycle ---------------------------------
    // Each is an arithmetic right shift of the product, taken AW bits wide; the
    // true value fits, so the slice of the sign-extended product is exact.
    wire signed [AW-1:0] xg_full  = mul_r[(16 - TQ) +: AW];   // (x * gain)  >> 11
    wire signed [AW-1:0] kfb_full = mul_r[14 +: AW];          // (k * fb)    >> 14
    wire signed [AW-1:0] inc_full = mul_r[(16 - TQ) +: AW];   // (g * diff)  >> 11
    wire signed [AW-1:0] out_full = mul_r[16 +: AW];          // ((y3>>5) * ogain) >> 16

    wire signed [AW-1:0] u_full = xg - kfb_full;
    wire signed [AW-1:0] ysum   = y[ys] + inc_full;
`ifdef INJECT_BUG_LADDER_SAT
    wire signed [SW-1:0] u    = u_full[SW-1:0];            // NEGATIVE CONTROL: wrap, no clamp
    wire signed [SW-1:0] ynew = ysum[SW-1:0];
`else
    wire signed [SW-1:0] u    = sat_s(u_full);
    wire signed [SW-1:0] ynew = sat_s(ysum);
`endif

    // ---- the one tanh unit ---------------------------------------------------
    // Request (combinational, in the cycle the argument is ready): magnitude,
    // clamp, index, fraction, the two table words. The interpolation multiply
    // goes through the shared multiplier; the result is assembled next cycle.
    wire signed [SW-1:0]  tin    = (step == 4'd2) ? u : ynew;
    wire                  tneg   = tin[SW-1];
    wire        [SW-1:0]  ta     = tneg ? -tin : tin;      // |v|; -(-2^23) = 2^23 fits unsigned
`ifdef INJECT_BUG_LADDER_TANH_CLAMP
    wire                  tsat   = 1'b0;                   // NEGATIVE CONTROL: index wraps past 4.0
`else
    wire                  tsat   = |ta[SW-1:SQ+2];         // |v| >= 4.0
`endif
    wire [TANH_LOG2N-1:0] tidx   = ta[SQ+1 -: TANH_LOG2N];
    wire [TANH_LOG2N:0]   tidx1  = {1'b0, tidx} + 1'b1;
    wire [FRACW-1:0]      tfrac  = ta[FRACW-1:0];
    wire signed [15:0]    t0     = rom[tidx];
    wire signed [15:0]    t1     = rom[tidx1];
    wire        [15:0]    tdelta = t1 - t0;                // monotonic table: 0..32767
    reg  signed [15:0]    t0_r;
    reg                   tneg_r, tsat_r;
    wire        [15:0]    tr_mag = tsat_r ? rom[N] : (t0_r + mul_r[FRACW +: 16]);
    wire signed [15:0]    tr     = tneg_r ? -tr_mag : tr_mag;

    // ---- sequencer -----------------------------------------------------------
    integer i;
    always @(posedge clk) begin
        if (!rst_n) begin
            for (i = 0; i < 4*NCH; i = i + 1) begin y[i] <= 0; w[i] <= 0; end
            for (i = 0; i < NCH; i = i + 1) begin d1[i] <= 0; d2[i] <= 0; end
            chr <= 0; y_ch <= 0; xg <= 0; step <= 4'd0; os <= 1'b0; busy <= 1'b0;
            y_out <= 0; y_valid <= 1'b0; mul_a <= 0; mul_b <= 0;
            t0_r <= 0; tneg_r <= 1'b0; tsat_r <= 1'b0;
        end else begin
            y_valid <= 1'b0;
            if (!busy) begin
                if (sample_valid) begin                  // load x * gain
                    busy <= 1'b1; os <= 1'b0; os2r <= os2x; step <= 4'd1; chr <= chsel;
                    mul_a <= x_in; mul_b <= gain;
                end
            end else case (step)
                4'd1: begin                              // xg; load k * fb
                    xg    <= xg_full[SW:0];
                    mul_a <= fb0; mul_b <= {3'b0, k};
                    step  <= 4'd2;
                end
                4'd2: begin                              // u = sat(xg - kfb); load tanh(u)
                    t0_r  <= t0; tneg_r <= tneg; tsat_r <= tsat;
                    mul_a <= tfrac; mul_b <= tdelta;
                    step  <= 4'd3;
                end
                4'd3, 4'd5, 4'd7, 4'd9: begin           // w_{s-1} = tanh result; load g * (w_{s-1} - w_s)
                    if (step != 4'd3) w[ysm1] <= tr;
                    mul_a <= tr - w[ys]; mul_b <= {4'b0, g};
                    step  <= step + 4'd1;
                end
                4'd4, 4'd6, 4'd8, 4'd10: begin          // y_s = sat(y_s + inc); load tanh(y_s)
                    y[ys] <= ynew;
                    t0_r  <= t0; tneg_r <= tneg; tsat_r <= tsat;
                    mul_a <= tfrac; mul_b <= tdelta;
                    step  <= step + 4'd1;
                end
                4'd11: begin                             // w_3 = tanh result; shift the delay line
                    w[y3i] <= tr; d2[dch] <= d1[dch]; d1[dch] <= y[y3i];
                    if (!os) begin
                        if (os2r) begin                   // pass 1: load k * fb from the new average
                            os <= 1'b1; mul_a <= fb1; mul_b <= {3'b0, k}; step <= 4'd2;
                        end else begin                    // one update at the actual high-rate sample
                            mul_a <= y[y3i] >>> TQ; mul_b <= ogain; step <= 4'd12;
                        end
                    end else begin                       // output: load (y_3 >> 5) * ogain
                        mul_a <= y[y3i] >>> TQ; mul_b <= ogain; step <= 4'd12;
                    end
                end
                default: begin                           // 12: y_out = sat16(product >> 16)
                    y_out <= sat_o(out_full); y_valid <= 1'b1; y_ch <= chr; busy <= 1'b0; step <= 4'd0;
                end
            endcase
        end
    end
endmodule
`default_nettype wire
