// Generated by tools/gen_rate_conv_2x.py. Do not hand-edit tap values.
// Causal 2x Q1.15 interpolation and 19-bit-output decimation, Q2.30 taps.
`default_nettype none
module rate_conv_2x (
    input wire clk, input wire rst_n,
    input wire interp_valid, input wire signed [15:0] x_in,
    output reg signed [16:0] x_even, output reg signed [16:0] x_odd,
    input wire decim_valid, input wire signed [18:0] y_even, y_odd,
    output reg signed [18:0] y_out
);
    function signed [31:0] interp_tap(input integer idx);
        begin
            case (idx)
                0: interp_tap = 32'sd0;
                1: interp_tap = -32'sd182065;
                2: interp_tap = 32'sd0;
                3: interp_tap = 32'sd962005;
                4: interp_tap = 32'sd0;
                5: interp_tap = -32'sd3074783;
                6: interp_tap = 32'sd0;
                7: interp_tap = 32'sd7694273;
                8: interp_tap = 32'sd0;
                9: interp_tap = -32'sd16531210;
                10: interp_tap = 32'sd0;
                11: interp_tap = 32'sd32095921;
                12: interp_tap = 32'sd0;
                13: interp_tap = -32'sd58630960;
                14: interp_tap = 32'sd0;
                15: interp_tap = 32'sd105792982;
                16: interp_tap = 32'sd0;
                17: interp_tap = -32'sd207949058;
                18: interp_tap = 32'sd0;
                19: interp_tap = 32'sd676691760;
                20: interp_tap = 32'sd1073745917;
                21: interp_tap = 32'sd676691760;
                22: interp_tap = 32'sd0;
                23: interp_tap = -32'sd207949058;
                24: interp_tap = 32'sd0;
                25: interp_tap = 32'sd105792982;
                26: interp_tap = 32'sd0;
                27: interp_tap = -32'sd58630960;
                28: interp_tap = 32'sd0;
                29: interp_tap = 32'sd32095921;
                30: interp_tap = 32'sd0;
                31: interp_tap = -32'sd16531210;
                32: interp_tap = 32'sd0;
                33: interp_tap = 32'sd7694273;
                34: interp_tap = 32'sd0;
                35: interp_tap = -32'sd3074783;
                36: interp_tap = 32'sd0;
                37: interp_tap = 32'sd962005;
                38: interp_tap = 32'sd0;
                39: interp_tap = -32'sd182065;
                40: interp_tap = 32'sd0;
                default: interp_tap = 32'sd0;
            endcase
        end
    endfunction
    function signed [31:0] decim_tap(input integer idx);
        begin
            case (idx)
                0: decim_tap = 32'sd0;
                1: decim_tap = -32'sd91033;
                2: decim_tap = 32'sd0;
                3: decim_tap = 32'sd481002;
                4: decim_tap = 32'sd0;
                5: decim_tap = -32'sd1537392;
                6: decim_tap = 32'sd0;
                7: decim_tap = 32'sd3847137;
                8: decim_tap = 32'sd0;
                9: decim_tap = -32'sd8265605;
                10: decim_tap = 32'sd0;
                11: decim_tap = 32'sd16047961;
                12: decim_tap = 32'sd0;
                13: decim_tap = -32'sd29315480;
                14: decim_tap = 32'sd0;
                15: decim_tap = 32'sd52896491;
                16: decim_tap = 32'sd0;
                17: decim_tap = -32'sd103974529;
                18: decim_tap = 32'sd0;
                19: decim_tap = 32'sd338345880;
                20: decim_tap = 32'sd536872959;
                21: decim_tap = 32'sd338345880;
                22: decim_tap = 32'sd0;
                23: decim_tap = -32'sd103974529;
                24: decim_tap = 32'sd0;
                25: decim_tap = 32'sd52896491;
                26: decim_tap = 32'sd0;
                27: decim_tap = -32'sd29315480;
                28: decim_tap = 32'sd0;
                29: decim_tap = 32'sd16047961;
                30: decim_tap = 32'sd0;
                31: decim_tap = -32'sd8265605;
                32: decim_tap = 32'sd0;
                33: decim_tap = 32'sd3847137;
                34: decim_tap = 32'sd0;
                35: decim_tap = -32'sd1537392;
                36: decim_tap = 32'sd0;
                37: decim_tap = 32'sd481002;
                38: decim_tap = 32'sd0;
                39: decim_tap = -32'sd91033;
                40: decim_tap = 32'sd0;
                default: decim_tap = 32'sd0;
            endcase
        end
    endfunction
    reg signed [15:0] xhist [0:19];
    reg signed [18:0] y0hist [0:19];
    reg signed [18:0] y1hist [0:19];
    reg signed [15:0] xsrc;
    reg signed [18:0] ysrc0, ysrc1;
    reg signed [55:0] acc_even, acc_odd, acc_decim;
    reg signed [55:0] rounded_even, rounded_odd, rounded_decim;
    integer j, k;

    always @* begin
        acc_even = 56'sd0;
        acc_odd = 56'sd0;
        for (j = 0; j <= 20; j = j + 1) begin
            if (j == 0) xsrc = x_in;
            else xsrc = xhist[j-1];
            acc_even = acc_even + ($signed(xsrc) * $signed(interp_tap(2*j)));
            if (j < 20)
                acc_odd = acc_odd + ($signed(xsrc) * $signed(interp_tap(2*j+1)));
        end
        rounded_even = (acc_even + 56'sd536870912) >>> 30;
        rounded_odd = (acc_odd + 56'sd536870912) >>> 30;
`ifdef INJECT_BUG_RATE_CONV_2X_CLAMP
        x_even = (rounded_even > 56'sd32767) ? 17'sd32767 :
                 (rounded_even < -56'sd32768) ? -17'sd32768 : rounded_even[16:0];
        x_odd = (rounded_odd > 56'sd32767) ? 17'sd32767 :
                (rounded_odd < -56'sd32768) ? -17'sd32768 : rounded_odd[16:0];
`else
        x_even = (rounded_even > 56'sd65535) ? 17'sd65535 :
                 (rounded_even < -56'sd65536) ? -17'sd65536 : rounded_even[16:0];
        x_odd = (rounded_odd > 56'sd65535) ? 17'sd65535 :
                (rounded_odd < -56'sd65536) ? -17'sd65536 : rounded_odd[16:0];
`endif

        acc_decim = 56'sd0;
        for (k = 0; k <= 20; k = k + 1) begin
            if (k == 0) ysrc0 = y_even;
            else ysrc0 = y0hist[k-1];
            acc_decim = acc_decim + ($signed(ysrc0) * $signed(decim_tap(2*k)));
            if (k < 20) begin
                ysrc1 = y1hist[k];
                acc_decim = acc_decim + ($signed(ysrc1) * $signed(decim_tap(2*k+1)));
            end
        end
        rounded_decim = (acc_decim + 56'sd536870912) >>> 30;
        y_out = (rounded_decim > 56'sd262143) ? 19'sd262143 :
                (rounded_decim < -56'sd262144) ? -19'sd262144 : rounded_decim[18:0];
    end

    integer i;
    always @(posedge clk) begin
        if (!rst_n) begin
            for (i = 0; i < 20; i = i + 1) begin
                xhist[i] <= 16'sd0;
                y0hist[i] <= 19'sd0;
                y1hist[i] <= 19'sd0;
            end
        end else begin
            if (interp_valid) begin
                for (i = 19; i > 0; i = i - 1) xhist[i] <= xhist[i-1];
                xhist[0] <= x_in;
            end
            if (decim_valid) begin
                for (i = 19; i > 0; i = i - 1) begin
                    y0hist[i] <= y0hist[i-1];
                    y1hist[i] <= y1hist[i-1];
                end
                y0hist[0] <= y_even;
                y1hist[0] <= y_odd;
            end
        end
    end
endmodule
`default_nettype wire
