// fpga/rtl/pads_rom.v -- GENERATED by fpga/pads_rom.py --write. DO NOT EDIT.
//
// The pads demo's ROMs (#449). `python3 fpga/pads_rom.py` re-derives this file
// and REFUSES a boot ROM whose kit does not hash to R1's frozen digest.
//   kit sha256 (drums_fx._kit_sha256 of boot entries 2..149): 321a93546cfa5ffab03b3cf91557580ea7655ada933ce380c81cd07597a9b683
//   source: fpga/release/r1-kit.json (uart_host.R1_KIT_SHA256)
//   voices: BTN0=BD, BTN1=SD, BTN2=CH, BTN3=CP; accent 1.0
//   LAT 704 frames (worst case needs 672); boot 152 writes
`default_nettype none
module pads_boot_rom (
    input  wire [7:0]  idx,
    output reg  [41:0] word,          // {flag, sec, addr[7:0], data[31:0]}
    output wire [7:0]  len,
    output wire [15:0] lat
);
    assign len = 8'd152;
    assign lat = 16'd704;
    always @(*) begin
        case (idx)
        8'd0: word = {1'b0, 1'b0, 8'h23, 32'h00000000};
        8'd1: word = {1'b0, 1'b1, 8'hFF, 32'h00000000};
        8'd2: word = {1'b0, 1'b1, 8'h20, 32'h0001184E};
        8'd3: word = {1'b0, 1'b1, 8'h21, 32'h0001F8A1};
        8'd4: word = {1'b0, 1'b1, 8'h22, 32'h00019F9C};
        8'd5: word = {1'b0, 1'b1, 8'h23, 32'h0002C9A9};
        8'd6: word = {1'b0, 1'b1, 8'h24, 32'h00044444};
        8'd7: word = {1'b0, 1'b1, 8'h25, 32'h0002E148};
        8'd8: word = {1'b0, 1'b1, 8'hB0, 32'h011A9D23};
        8'd9: word = {1'b0, 1'b1, 8'hB1, 32'h0324D110};
        8'd10: word = {1'b0, 1'b1, 8'hB2, 32'h00000000};
        8'd11: word = {1'b0, 1'b1, 8'hB3, 32'h00000001};
        8'd12: word = {1'b0, 1'b1, 8'hB4, 32'h00DA1B85};
        8'd13: word = {1'b0, 1'b1, 8'hB5, 32'h0355D5AE};
        8'd14: word = {1'b0, 1'b1, 8'hB6, 32'h00007333};
        8'd15: word = {1'b0, 1'b1, 8'hB7, 32'h00000002};
        8'd16: word = {1'b0, 1'b1, 8'hB8, 32'h000ECC30};
        8'd17: word = {1'b0, 1'b1, 8'hB9, 32'h037543CC};
        8'd18: word = {1'b0, 1'b1, 8'hBA, 32'h0000B0A4};
        8'd19: word = {1'b0, 1'b1, 8'hBB, 32'h00000002};
        8'd20: word = {1'b0, 1'b1, 8'hBC, 32'h01728A19};
        8'd21: word = {1'b0, 1'b1, 8'hBD, 32'h0366ECC6};
        8'd22: word = {1'b0, 1'b1, 8'hBE, 32'h000034B6};
        8'd23: word = {1'b0, 1'b1, 8'hBF, 32'h00000001};
        8'd24: word = {1'b0, 1'b1, 8'hC0, 32'h01E53ED0};
        8'd25: word = {1'b0, 1'b1, 8'hC1, 32'h031579F2};
        8'd26: word = {1'b0, 1'b1, 8'hC2, 32'h00000000};
        8'd27: word = {1'b0, 1'b1, 8'hC3, 32'h00000001};
        8'd28: word = {1'b0, 1'b1, 8'hC4, 32'h01EDD6CC};
        8'd29: word = {1'b0, 1'b1, 8'hC5, 32'h030CD4FE};
        8'd30: word = {1'b0, 1'b1, 8'hC6, 32'h00000592};
        8'd31: word = {1'b0, 1'b1, 8'hC7, 32'h00000001};
        8'd32: word = {1'b0, 1'b1, 8'hD0, 32'h01FFEA42};
        8'd33: word = {1'b0, 1'b1, 8'hD1, 32'h03001300};
        8'd34: word = {1'b0, 1'b1, 8'hD2, 32'h000000D9};
        8'd35: word = {1'b0, 1'b1, 8'hD3, 32'h00000000};
        8'd36: word = {1'b0, 1'b1, 8'hD4, 32'h01FF8366};
        8'd37: word = {1'b0, 1'b1, 8'hD5, 32'h03005AFC};
        8'd38: word = {1'b0, 1'b1, 8'hD6, 32'h000000AF};
        8'd39: word = {1'b0, 1'b1, 8'hD7, 32'h00000000};
        8'd40: word = {1'b0, 1'b1, 8'hD8, 32'h01FE5EB2};
        8'd41: word = {1'b0, 1'b1, 8'hD9, 32'h03012282};
        8'd42: word = {1'b0, 1'b1, 8'hDA, 32'h00000245};
        8'd43: word = {1'b0, 1'b1, 8'hDB, 32'h00000000};
        8'd44: word = {1'b0, 1'b1, 8'hDC, 32'h01FFD807};
        8'd45: word = {1'b0, 1'b1, 8'hDD, 32'h03001EE0};
        8'd46: word = {1'b0, 1'b1, 8'hDE, 32'h0000013B};
        8'd47: word = {1'b0, 1'b1, 8'hDF, 32'h00000000};
        8'd48: word = {1'b0, 1'b1, 8'hE0, 32'h01FFBB4C};
        8'd49: word = {1'b0, 1'b1, 8'hE1, 32'h0300303D};
        8'd50: word = {1'b0, 1'b1, 8'hE2, 32'h00000196};
        8'd51: word = {1'b0, 1'b1, 8'hE3, 32'h00000000};
        8'd52: word = {1'b0, 1'b1, 8'hE4, 32'h01FF9A1F};
        8'd53: word = {1'b0, 1'b1, 8'hE5, 32'h03003F74};
        8'd54: word = {1'b0, 1'b1, 8'hE6, 32'h0000028B};
        8'd55: word = {1'b0, 1'b1, 8'hE7, 32'h00000000};
        8'd56: word = {1'b0, 1'b1, 8'hE8, 32'h01FCD356};
        8'd57: word = {1'b0, 1'b1, 8'hE9, 32'h030243FF};
        8'd58: word = {1'b0, 1'b1, 8'hEA, 32'h00000000};
        8'd59: word = {1'b0, 1'b1, 8'hEB, 32'h00000000};
        8'd60: word = {1'b0, 1'b1, 8'hEC, 32'h01EDC70C};
        8'd61: word = {1'b0, 1'b1, 8'hED, 32'h03046527};
        8'd62: word = {1'b0, 1'b1, 8'hEE, 32'h00000000};
        8'd63: word = {1'b0, 1'b1, 8'hEF, 32'h00000000};
        8'd64: word = {1'b0, 1'b1, 8'hC8, 32'h01BB8EB8};
        8'd65: word = {1'b0, 1'b1, 8'hC9, 32'h031293A2};
        8'd66: word = {1'b0, 1'b1, 8'hCA, 32'h00000000};
        8'd67: word = {1'b0, 1'b1, 8'hCB, 32'h00000001};
        8'd68: word = {1'b0, 1'b1, 8'hCC, 32'h004BE113};
        8'd69: word = {1'b0, 1'b1, 8'hCD, 32'h036C44A6};
        8'd70: word = {1'b0, 1'b1, 8'hCE, 32'h0000FFFF};
        8'd71: word = {1'b0, 1'b1, 8'hCF, 32'h00000001};
        8'd72: word = {1'b0, 1'b1, 8'h40, 32'h000000F0};
        8'd73: word = {1'b0, 1'b1, 8'h41, 32'h00400000};
        8'd74: word = {1'b0, 1'b1, 8'h42, 32'h00003025};
        8'd75: word = {1'b0, 1'b1, 8'h44, 32'h000030F0};
        8'd76: word = {1'b0, 1'b1, 8'h45, 32'h000F5C29};
        8'd77: word = {1'b0, 1'b1, 8'h46, 32'h0000FFFF};
        8'd78: word = {1'b0, 1'b1, 8'h48, 32'h000000F1};
        8'd79: word = {1'b0, 1'b1, 8'h49, 32'h00400000};
        8'd80: word = {1'b0, 1'b1, 8'h4A, 32'h00003025};
        8'd81: word = {1'b0, 1'b1, 8'h4C, 32'h000000F1};
        8'd82: word = {1'b0, 1'b1, 8'h4D, 32'h004DFA44};
        8'd83: word = {1'b0, 1'b1, 8'h4E, 32'h0000002D};
        8'd84: word = {1'b0, 1'b1, 8'h50, 32'h000000F2};
        8'd85: word = {1'b0, 1'b1, 8'h51, 32'h00400000};
        8'd86: word = {1'b0, 1'b1, 8'h52, 32'h00003025};
        8'd87: word = {1'b0, 1'b1, 8'h70, 32'h000000F8};
        8'd88: word = {1'b0, 1'b1, 8'h71, 32'h00400000};
        8'd89: word = {1'b0, 1'b1, 8'h72, 32'h00003025};
        8'd90: word = {1'b0, 1'b1, 8'h54, 32'h000000F3};
        8'd91: word = {1'b0, 1'b1, 8'h55, 32'h00400000};
        8'd92: word = {1'b0, 1'b1, 8'h56, 32'h00003025};
        8'd93: word = {1'b0, 1'b1, 8'h58, 32'h000000F4};
        8'd94: word = {1'b0, 1'b1, 8'h59, 32'h00FFFFFF};
        8'd95: word = {1'b0, 1'b1, 8'h5A, 32'h00000044};
        8'd96: word = {1'b0, 1'b1, 8'h5C, 32'h00000045};
        8'd97: word = {1'b0, 1'b1, 8'h5D, 32'h00FFFFFF};
        8'd98: word = {1'b0, 1'b1, 8'h5E, 32'h00000009};
        8'd99: word = {1'b0, 1'b1, 8'h60, 32'h07FF00F6};
        8'd100: word = {1'b0, 1'b1, 8'h61, 32'h00B0A3D6};
        8'd101: word = {1'b0, 1'b1, 8'h62, 32'h00000154};
        8'd102: word = {1'b0, 1'b1, 8'h63, 32'h00000044};
        8'd103: word = {1'b0, 1'b1, 8'h64, 32'h000000F6};
        8'd104: word = {1'b0, 1'b1, 8'h65, 32'h003851EB};
        8'd105: word = {1'b0, 1'b1, 8'h66, 32'h00000011};
        8'd106: word = {1'b0, 1'b1, 8'h68, 32'h000000F7};
        8'd107: word = {1'b0, 1'b1, 8'h69, 32'h00800000};
        8'd108: word = {1'b0, 1'b1, 8'h6A, 32'h00000110};
        8'd109: word = {1'b0, 1'b1, 8'h6C, 32'h000000F7};
        8'd110: word = {1'b0, 1'b1, 8'h6D, 32'h00800000};
        8'd111: word = {1'b0, 1'b1, 8'h6E, 32'h0000000E};
        8'd112: word = {1'b0, 1'b1, 8'h74, 32'h000000F9};
        8'd113: word = {1'b0, 1'b1, 8'h75, 32'h000F5C29};
        8'd114: word = {1'b0, 1'b1, 8'h76, 32'h00003025};
        8'd115: word = {1'b0, 1'b1, 8'h78, 32'h000000F9};
        8'd116: word = {1'b0, 1'b1, 8'h79, 32'h0057CED9};
        8'd117: word = {1'b0, 1'b1, 8'h7A, 32'h0000003E};
        8'd118: word = {1'b0, 1'b1, 8'h7C, 32'h000000FA};
        8'd119: word = {1'b0, 1'b1, 8'h7D, 32'h0052F1AA};
        8'd120: word = {1'b0, 1'b1, 8'h7E, 32'h00000072};
        8'd121: word = {1'b0, 1'b1, 8'h80, 32'h000000FA};
        8'd122: word = {1'b0, 1'b1, 8'h81, 32'h006E978D};
        8'd123: word = {1'b0, 1'b1, 8'h82, 32'h0000000A};
        8'd124: word = {1'b0, 1'b1, 8'h84, 32'h000000FA};
        8'd125: word = {1'b0, 1'b1, 8'h85, 32'h00161E4F};
        8'd126: word = {1'b0, 1'b1, 8'h86, 32'h00000003};
        8'd127: word = {1'b0, 1'b1, 8'h90, 32'h00807803};
        8'd128: word = {1'b0, 1'b1, 8'h91, 32'h01F07823};
        8'd129: word = {1'b0, 1'b1, 8'h92, 32'h00907843};
        8'd130: word = {1'b0, 1'b1, 8'h93, 32'h00A07843};
        8'd131: word = {1'b0, 1'b1, 8'h94, 32'h00307861};
        8'd132: word = {1'b0, 1'b1, 8'h95, 32'h00B07883};
        8'd133: word = {1'b0, 1'b1, 8'h96, 32'h00C07983};
        8'd134: word = {1'b0, 1'b1, 8'h97, 32'h00D078A3};
        8'd135: word = {1'b0, 1'b1, 8'h98, 32'h00007BE2};
        8'd136: word = {1'b0, 1'b1, 8'h99, 32'h0020F8D0};
        8'd137: word = {1'b0, 1'b1, 8'h9A, 32'h0010F8F0};
        8'd138: word = {1'b0, 1'b1, 8'h9B, 32'h00407BE1};
        8'd139: word = {1'b0, 1'b1, 8'h9C, 32'h01F12514};
        8'd140: word = {1'b0, 1'b1, 8'h9D, 32'h0050AD49};
        8'd141: word = {1'b0, 1'b1, 8'h9E, 32'h0050AD4A};
        8'd142: word = {1'b0, 1'b1, 8'h9F, 32'h00E079A3};
        8'd143: word = {1'b0, 1'b1, 8'hA0, 32'h00F079A3};
        8'd144: word = {1'b0, 1'b1, 8'hA1, 32'h01F0F9DE};
        8'd145: word = {1'b0, 1'b1, 8'hA2, 32'h01F0F9DF};
        8'd146: word = {1'b0, 1'b1, 8'hA3, 32'h00607BE2};
        8'd147: word = {1'b0, 1'b1, 8'hA4, 32'h0020F9F0};
        8'd148: word = {1'b0, 1'b1, 8'hA5, 32'h0070FA10};
        8'd149: word = {1'b0, 1'b1, 8'hA6, 32'h01F0FA36};
        8'd150: word = {1'b0, 1'b0, 8'h0E, 32'h0000399A};
        8'd151: word = {1'b0, 1'b0, 8'h2C, 32'h0000399A};
        default: word = 42'd0;
        endcase
    end
endmodule

// One lookup per button; kind 0 = plain write, 1 = stops rise, 2 = stops drop
// (for 1 and 2 the data field is the stop's bit; the sender merges it into its
// shadow of the stops mask).
module pads_hit_rom (
    input  wire [1:0]  voice,
    input  wire [2:0]  step,
    output reg  [51:0] word,          // {kind[1:0], off[7:0], flag, sec, addr[7:0], data[31:0]}
    output reg  [2:0]  len,
    output reg  [7:0]  last_off
);
    always @(*) begin
        case (voice)
        2'd0: begin len = 3'd7; last_off = 8'd192; end   // BD
        2'd1: begin len = 3'd3; last_off = 8'd1; end   // SD
        2'd2: begin len = 3'd3; last_off = 8'd1; end   // CH
        2'd3: begin len = 3'd3; last_off = 8'd1; end   // CP
        default: begin len = 3'd0; last_off = 8'd0; end
        endcase
        case ({voice, step})
        {2'd0, 3'd0}: word = {2'd0, 8'd0, 1'b0, 1'b1, 8'hD0, 32'h01FF3350};
        {2'd0, 3'd1}: word = {2'd0, 8'd0, 1'b0, 1'b1, 8'hD1, 32'h0300B99B};
        {2'd0, 3'd2}: word = {2'd0, 8'd0, 1'b0, 1'b1, 8'h10, 32'h00008000};
        {2'd0, 3'd3}: word = {2'd1, 8'd0, 1'b0, 1'b1, 8'h00, 32'h00000001};
        {2'd0, 3'd4}: word = {2'd2, 8'd1, 1'b0, 1'b1, 8'h00, 32'h00000001};
        {2'd0, 3'd5}: word = {2'd0, 8'd192, 1'b0, 1'b1, 8'hD0, 32'h01FFEA42};
        {2'd0, 3'd6}: word = {2'd0, 8'd192, 1'b0, 1'b1, 8'hD1, 32'h03001300};
        {2'd1, 3'd0}: word = {2'd0, 8'd0, 1'b0, 1'b1, 8'h11, 32'h00008000};
        {2'd1, 3'd1}: word = {2'd1, 8'd0, 1'b0, 1'b1, 8'h00, 32'h00000002};
        {2'd1, 3'd2}: word = {2'd2, 8'd1, 1'b0, 1'b1, 8'h00, 32'h00000002};
        {2'd2, 3'd0}: word = {2'd0, 8'd0, 1'b0, 1'b1, 8'h14, 32'h00008000};
        {2'd2, 3'd1}: word = {2'd1, 8'd0, 1'b0, 1'b1, 8'h00, 32'h00000010};
        {2'd2, 3'd2}: word = {2'd2, 8'd1, 1'b0, 1'b1, 8'h00, 32'h00000010};
        {2'd3, 3'd0}: word = {2'd0, 8'd0, 1'b0, 1'b1, 8'h16, 32'h00008000};
        {2'd3, 3'd1}: word = {2'd1, 8'd0, 1'b0, 1'b1, 8'h00, 32'h00000040};
        {2'd3, 3'd2}: word = {2'd2, 8'd1, 1'b0, 1'b1, 8'h00, 32'h00000040};
        default: word = 52'd0;
        endcase
    end
endmodule
`default_nettype wire
