create_generated_clock -name i2s_bclk_ext -source [get_pins hardware_clock.mmcm/CLKOUT0] -divide_by 4 [get_ports i2s_bclk]
set_output_delay -clock i2s_bclk_ext -max 8.200 [get_ports i2s_sdata]
set_output_delay -clock i2s_bclk_ext -min 154.560 [get_ports i2s_sdata]
set_output_delay -clock i2s_bclk_ext -max 8.200 [get_ports i2s_lrclk]
set_output_delay -clock i2s_bclk_ext -min 154.560 [get_ports i2s_lrclk]
set_output_delay -clock hardware_clock.clock_raw -max 54.958 [get_ports spi_miso]
set_output_delay -clock hardware_clock.clock_raw -min 0.000 [get_ports spi_miso]
set_output_delay -clock hardware_clock.clock_raw -max 0.000 [get_ports {led[1] led[2] led[3]}]
set_output_delay -clock hardware_clock.clock_raw -min 0.000 [get_ports {led[1] led[2] led[3]}]
