#!/usr/bin/env python3
"""Generate the fixed-coefficient, causal 2x FIR converter RTL."""
from __future__ import annotations

import argparse
import pathlib
import sys

import numpy as np
from scipy.signal import firwin

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "rtl-sketch/rate_conv_2x.v"
Q = 30


def _function(name: str, values: np.ndarray) -> str:
    lines = [f"    function signed [31:0] {name}(input integer idx);", "        begin", "            case (idx)"]
    lines.extend(f"                {i}: {name} = 32'sd{int(value)};"
                 if value >= 0 else f"                {i}: {name} = -32'sd{abs(int(value))};"
                 for i, value in enumerate(values))
    lines.extend([f"                default: {name} = 32'sd0;",
                  "            endcase", "        end", "    endfunction"])
    return "\n".join(lines)


def generate() -> str:
    prototype = firwin(41, 0.5, window=("kaiser", 8.6))
    interp = np.rint(2.0 * prototype * (1 << Q)).astype(np.int64)
    decim = np.rint(prototype * (1 << Q)).astype(np.int64)
    return '''// Generated by tools/gen_rate_conv_2x.py. Do not hand-edit tap values.
// Causal 2x Q1.15 interpolation and 19-bit-output decimation, Q2.30 taps.
`default_nettype none
module rate_conv_2x (
    input wire clk, input wire rst_n,
    input wire interp_valid, input wire signed [15:0] x_in,
    output reg signed [16:0] x_even, output reg signed [16:0] x_odd,
    input wire decim_valid, input wire signed [18:0] y_even, y_odd,
    output reg signed [18:0] y_out
);
''' + _function("interp_tap", interp) + "\n" + _function("decim_tap", decim) + '''
    reg signed [15:0] xhist [0:19];
    reg signed [18:0] y0hist [0:19];
    reg signed [18:0] y1hist [0:19];
    reg signed [15:0] xsrc;
    reg signed [18:0] ysrc0, ysrc1;
    reg signed [55:0] acc_even, acc_odd, acc_decim;
    reg signed [55:0] rounded_even, rounded_odd, rounded_decim;
    integer j, k;

    always @* begin
        acc_even = 56'sd0;
        acc_odd = 56'sd0;
        for (j = 0; j <= 20; j = j + 1) begin
            if (j == 0) xsrc = x_in;
            else xsrc = xhist[j-1];
            acc_even = acc_even + ($signed(xsrc) * $signed(interp_tap(2*j)));
            if (j < 20)
                acc_odd = acc_odd + ($signed(xsrc) * $signed(interp_tap(2*j+1)));
        end
        rounded_even = (acc_even + 56'sd536870912) >>> 30;
        rounded_odd = (acc_odd + 56'sd536870912) >>> 30;
`ifdef INJECT_BUG_RATE_CONV_2X_CLAMP
        x_even = (rounded_even > 56'sd32767) ? 17'sd32767 :
                 (rounded_even < -56'sd32768) ? -17'sd32768 : rounded_even[16:0];
        x_odd = (rounded_odd > 56'sd32767) ? 17'sd32767 :
                (rounded_odd < -56'sd32768) ? -17'sd32768 : rounded_odd[16:0];
`else
        x_even = (rounded_even > 56'sd65535) ? 17'sd65535 :
                 (rounded_even < -56'sd65536) ? -17'sd65536 : rounded_even[16:0];
        x_odd = (rounded_odd > 56'sd65535) ? 17'sd65535 :
                (rounded_odd < -56'sd65536) ? -17'sd65536 : rounded_odd[16:0];
`endif

        acc_decim = 56'sd0;
        for (k = 0; k <= 20; k = k + 1) begin
            if (k == 0) ysrc0 = y_even;
            else ysrc0 = y0hist[k-1];
            acc_decim = acc_decim + ($signed(ysrc0) * $signed(decim_tap(2*k)));
            if (k < 20) begin
                ysrc1 = y1hist[k];
                acc_decim = acc_decim + ($signed(ysrc1) * $signed(decim_tap(2*k+1)));
            end
        end
        rounded_decim = (acc_decim + 56'sd536870912) >>> 30;
        y_out = (rounded_decim > 56'sd262143) ? 19'sd262143 :
                (rounded_decim < -56'sd262144) ? -19'sd262144 : rounded_decim[18:0];
    end

    integer i;
    always @(posedge clk) begin
        if (!rst_n) begin
            for (i = 0; i < 20; i = i + 1) begin
                xhist[i] <= 16'sd0;
                y0hist[i] <= 19'sd0;
                y1hist[i] <= 19'sd0;
            end
        end else begin
            if (interp_valid) begin
                for (i = 19; i > 0; i = i - 1) xhist[i] <= xhist[i-1];
                xhist[0] <= x_in;
            end
            if (decim_valid) begin
                for (i = 19; i > 0; i = i - 1) begin
                    y0hist[i] <= y0hist[i-1];
                    y1hist[i] <= y1hist[i-1];
                end
                y0hist[0] <= y_even;
                y1hist[0] <= y_odd;
            end
        end
    end
endmodule
`default_nettype wire
'''


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--out", type=pathlib.Path, default=OUT)
    args = parser.parse_args(argv)
    expected = generate()
    if args.check:
        if not args.out.exists() or args.out.read_text() != expected:
            print(f"generated RTL differs: {args.out}")
            return 1
    else:
        args.out.write_text(expected)
    print(f"rate_conv_2x: {'verified' if args.check else 'generated'} {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
