#!/usr/bin/env python3
"""The sawtooth's aliasing AFTER the 2x decimation filter (issue #61).

    python3 tools/measure_saw_alias_after_2x.py --out docs/saw-alias-2x-results.json

Issue #61 tracked "our oscillators alias 19-32 dB more than both references".
Its own comment trail withdrew most of those magnitudes, the fix direction it
settled on -- a decimation filter, not a longer BLEP -- shipped for the saw
(`voice_fx._render_2x`, `_DECIM2_TAPS`, selected as `OSC2X=1` in
`fpga/SELECTED.md`), and then nobody measured the fixed path against the
references. `model/test_moog_acceptance.py` still locked only the UNFIXED
curve. This is the "after" measurement that docstring said somebody owed.

WHAT THIS MEASURES, AND WHAT IT REFUSES TO MEASURE
--------------------------------------------------
Two register sets, for two different questions, kept apart because they cannot
answer each other's:

  ALIAS_CURVE registers   MIDI 40, 52, 64, 76, 88, 100 -- the six the locked
                          "before" test uses. Base rate vs the 2x-decimated
                          path, ours against ours. No reference reading exists
                          at these pitches and none is invented.
  reference registers     MIDI 33, 45, 57, 69, 81, 93 (55 Hz .. 1760 Hz) --
                          the six `model/reference_voice.py` renders, and the
                          ONLY pitches at which a Surge XT or Mini V3 reading
                          exists in this repository.

**The references are not re-rendered here and cannot be.** `reference_rigs`
hosts VST3 plugins through `dawdreamer` from `/Library/Audio/Plug-Ins/VST3`;
this is a Linux build host with neither. The reference rows are read from the
frozen artefact `docs/reference-voice-report.txt`, whose provenance is checked
before a single margin is computed. If you pass `--live-refs` on a host that
has the plugins, the rigs are used instead and the frozen table becomes the
control.

THREE PRECONDITIONS, ASSERTED AT THE POINT OF USE
-------------------------------------------------
Each one REFUSES rather than reports, because each has already been the cause
of a published wrong number in this repository:

  1. **The 2x path measured here is the path that ships.** The oscillator
     output of a real `VoiceFx(oversample_2x=True)` note is compared sample for
     sample against the `_render_2x` call this module makes. #61's sibling
     lesson: every bench drove the register write port rather than the link.
  2. **The frozen reference table was made with a DIFFERENT estimator.**
     `docs/reference-voice-report.txt` was written by commit 74ce6a0 (#87,
     2026-09-18); `inharmonic_fraction_db` was rewindowed from Hann to
     Blackman-Harris later the same day by ba14af2 (#132), and the report was
     never regenerated. So the report's own instrument is reconstructed from
     its own commit (`git show 74ce6a0:model/audio_measure.py`) and every
     margin against a reference row is computed with THAT instrument, on both
     sides. It is accepted only if it reproduces the report's own `ours/saw`
     and `ideal/saw` rows to 0.15 dB -- if it does not, the two tables are not
     the same measurement and no margin is printed.
  3. **`docs/reference-voice-results.json` is refused outright.** It is the
     machine-readable half of the same study and it was NOT regenerated by
     #87: its Surge rows still read the flat "-60 dB at every pitch" that #87
     identified as the harness's own leftover note tails. Reading it would
     reproduce a withdrawn figure. The refusal is explicit so the next person
     does not have to rediscover it.

Every reading carries `detail['headroom_db']` -- the value above the
estimator's own per-call floor. A reading with less than 3 dB of headroom is
reported as a LIMIT, never as a value, and any margin that uses it is a bound.
The 55 Hz column of this issue was withdrawn once already for exactly this.

Everything here is measurement. It changes no shipped behaviour.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import math
import os
import pathlib
import re
import subprocess
import sys
import tempfile
import time

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "model"))
sys.path.insert(0, str(ROOT / "audition"))

import audio_measure as am                                          # noqa: E402
import voice_fx as vf                                               # noqa: E402

SR = vf.SR
FS = 32768.0
SECONDS = 0.5
WARMUP = 256                     # frames, to fill the decimator's 30-tap history

# The six registers the locked "before" test uses (test_moog_acceptance.py).
ALIAS_NOTES = (40, 52, 64, 76, 88, 100)
# The six `model/reference_voice.py` renders, and the only ones a reference
# reading exists at: A1 .. A6.
REFERENCE_NOTES = (33, 45, 57, 69, 81, 93)

# The commit that wrote docs/reference-voice-report.txt, and therefore the
# commit whose `inharmonic_fraction_db` every number in it was measured with.
REPORT_COMMIT = "74ce6a03333cc6dbd2a783d8bacc7f8ba7e34ba4"
REPORT_PATH = "docs/reference-voice-report.txt"
REPORT_DATE = "2026-09-18"
# Refused, with the reason, rather than silently unused.
STALE_JSON = "docs/reference-voice-results.json"

MIN_HEADROOM_DB = 3.0            # below this a reading is the estimator, not the signal
REPRODUCTION_TOL_DB = 0.15       # the frozen table's own rows must come back


class Refused(RuntimeError):
    """A precondition failed. This is a first-class outcome, not a failure to
    measure: it means the apparatus was in a state where any number it printed
    would look exactly like data."""


# ---------------------------------------------------------------------------
# provenance
# ---------------------------------------------------------------------------
def _git(*a: str) -> str:
    try:
        return subprocess.run(["git", *a], cwd=str(ROOT), capture_output=True,
                              text=True, timeout=60).stdout.strip()
    except Exception as e:                                          # pragma: no cover
        return f"<unavailable: {e}>"


def provenance(argv=None) -> dict:
    """Every dB figure this repository publishes has to name the commit it was
    measured against (issue #61's own acceptance criteria). `dirty` is part of
    that: a number measured on an uncommitted tree names no commit at all."""
    diff = _git("diff", "HEAD")
    return dict(commit=_git("rev-parse", "HEAD"),
                branch=_git("rev-parse", "--abbrev-ref", "HEAD"),
                dirty=bool(diff),
                command=" ".join(argv or sys.argv),
                utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                python=sys.version.split()[0], numpy=np.__version__,
                seconds=SECONDS, warmup_frames=WARMUP, sr=SR)


# ---------------------------------------------------------------------------
# the two renders: base rate, and the shipped 2x-decimated path
# ---------------------------------------------------------------------------
def render_base(note: int, n: int = None, shape: str = "saw") -> tuple[np.ndarray, float]:
    """The base-rate oscillator, exactly as `test_moog_acceptance._osc` builds
    it. `f0` is derived from the QUANTISED increment, not from the commanded
    Hz, because that is the frequency the signal actually has."""
    n = int(SECONDS * SR) if n is None else n
    inc = vf.phase_inc(vf.note_hz(note))
    f0 = inc * SR / (1 << 24)
    return vf.OscFx(shape, True).render(n, inc).astype(np.float64) / FS, f0


def render_2x(note: int, n: int = None, shape: str = "saw",
              warmup: int = WARMUP) -> tuple[np.ndarray, float]:
    """The shipped `oversample_2x=True` oscillator: PolyBLEP at 2x, the 31-tap
    half-band FIR, then every second sample.

    The decimator carries 30 samples of history between calls, so a cold start
    fades the first 30 samples in from silence. `warmup` frames are rendered
    and discarded first, which is what a held note does in the voice."""
    n = int(SECONDS * SR) if n is None else n
    inc = vf.phase_inc(vf.note_hz(note))
    f0 = inc * SR / (1 << 24)
    osc = vf.OscFx(shape, True)
    hist = np.zeros(len(vf._DECIM2_TAPS) - 1, dtype=np.int64)
    phase2 = 0
    if warmup:
        _, hist, phase2 = vf._render_2x(osc, warmup, inc, hist, phase2)
    y, hist, phase2 = vf._render_2x(osc, n, inc, hist, phase2)
    return y.astype(np.float64) / FS, f0


def render_2x_drop(note: int, n: int = None) -> tuple[np.ndarray, float]:
    """CONTROL: the same 2x oscillator reduced by KEEPING THE LAST SUB-STEP
    instead of filtering -- issue #80's defect, and the thing `_DECIM2_TAPS`
    exists to replace. Present so that a green "after" number has something it
    is green *against*: this control must read far worse than the base rate."""
    n = int(SECONDS * SR) if n is None else n
    inc = vf.phase_inc(vf.note_hz(note))
    f0 = inc * SR / (1 << 24)
    hi = vf.OscFx("saw", True).render(2 * n, inc // 2).astype(np.float64) / FS
    return hi[1::2], f0


# ---------------------------------------------------------------------------
# precondition 1: what is measured here is what ships
# ---------------------------------------------------------------------------
def assert_shipped_path(note: int = 76) -> dict:
    """Drive a real `VoiceFx(oversample_2x=True)` note and compare its
    oscillator trace, sample for sample, with the `_render_2x` call this module
    makes on the same increments.

    Not a formality. `voice_fx._render` gates the 2x chain on the SHAPE
    (`saw`, or a rectangle only when `oversample_pulse_2x`), keeps the
    decimator history per oscillator, and advances a second phase accumulator
    for the oscillators that do not take the chain. A module-level helper that
    silently diverged from any of that would measure a path nobody ships."""
    v = vf.VoiceFx(oversample_2x=True)
    v.note(note, 0.6, waves=("saw", "saw", "saw"), detune=(0.0, 0.0, 0.0),
           mix=(1.0, 0.0, 0.0), noise=0.0, drift_cents=0.0,
           mod_mix=0.0, mod_wheel=0.0, glide_s=0)
    shipped = np.asarray(v.trace["osc"][0], dtype=np.int64)
    incs = np.asarray(v.trace["incs"][0], dtype=np.int64)
    osc = vf.OscFx("saw", True)
    hist = np.zeros(len(vf._DECIM2_TAPS) - 1, dtype=np.int64)
    here, _, _ = vf._render_2x(osc, len(shipped), incs, hist, 0)
    worst = int(np.abs(shipped - np.asarray(here, dtype=np.int64)).max())
    if worst != 0:
        raise Refused(
            "the 2x oscillator measured here is NOT the one VoiceFx(oversample_2x=True) "
            f"renders: worst sample difference {worst} LSB at note {note}")
    # ...and the gate is real: with the flag off, the trace must differ.
    w = vf.VoiceFx(oversample_2x=False)
    w.note(note, 0.6, waves=("saw", "saw", "saw"), detune=(0.0, 0.0, 0.0),
           mix=(1.0, 0.0, 0.0), noise=0.0, drift_cents=0.0,
           mod_mix=0.0, mod_wheel=0.0, glide_s=0)
    off = np.asarray(w.trace["osc"][0], dtype=np.int64)
    if np.array_equal(off, shipped):
        raise Refused("oversample_2x=True and oversample_2x=False render the same "
                      "oscillator output -- the flag is not selecting anything")
    return dict(name="shipped_path_is_the_measured_path", ok=True, note=note,
                worst_lsb=worst,
                off_vs_on_max_lsb=int(np.abs(off - shipped).max()))


# ---------------------------------------------------------------------------
# precondition 2: the frozen table's own instrument
# ---------------------------------------------------------------------------
def load_report_estimator(commit: str = REPORT_COMMIT):
    """`model/audio_measure.py` AS IT WAS at the commit that wrote the frozen
    reference table -- Hann-windowed, floor quoted rather than measured.

    Not a reimplementation: the file itself, out of git. A reimplementation is
    a second chance to be wrong about the instrument, which is the class of
    mistake this whole issue is made of."""
    src = subprocess.run(["git", "show", f"{commit}:model/audio_measure.py"],
                         cwd=str(ROOT), capture_output=True, text=True, timeout=60)
    if src.returncode != 0 or not src.stdout.strip():
        raise Refused(f"cannot read model/audio_measure.py at {commit[:7]}: "
                      f"{src.stderr.strip() or 'empty'}")
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="am-report-")) / "audio_measure_report.py"
    tmp.write_text(src.stdout)
    spec = importlib.util.spec_from_file_location("audio_measure_report", tmp)
    mod = importlib.util.module_from_spec(spec)
    # `@dataclass` resolves its own module out of sys.modules while the class
    # body executes, so the module has to be registered before it is run.
    sys.modules["audio_measure_report"] = mod
    spec.loader.exec_module(mod)
    return mod


def _report_read(mod, y: np.ndarray, f0_cmd: float) -> float:
    """One reading through the frozen table's own pipeline: refine f0 from the
    signal (the report does; assuming it was #87's third apparatus fault), then
    the Hann-windowed inharmonic fraction."""
    fe = mod.refine_f0(y, f0_cmd, SR)
    f0 = fe.value if fe.ok else f0_cmd
    est = mod.inharmonic_fraction_db(y, f0, SR)
    if not est.ok:
        raise Refused(f"the report's own estimator refused at f0={f0_cmd:.1f}: {est.reason}")
    return float(est.value)


def assert_report_instrument(mod, table: dict) -> dict:
    """The reconstructed instrument must reproduce the frozen table's OWN rows.

    `ours/saw` and `ideal/saw` are the two rows in that table this host can
    re-render from source, so they are the only available check that the
    reconstruction is the instrument the Surge and Mini V3 rows were read with.
    If they come back, the reference rows are on the same footing as ours and a
    margin means something. If they do not, nothing in the table is comparable
    with anything measured today."""
    checks = []
    worst = 0.0
    for device, render in (("ours", lambda nt: (vf.OscFx("saw", True).render(
            int(SECONDS * SR), vf.phase_inc(vf.note_hz(nt))).astype(np.float64) / FS,
            vf.note_hz(nt))),
            ("ideal", lambda nt: _ideal("saw", nt))):
        row = table.get((device, "saw"))
        if row is None:
            raise Refused(f"the frozen table has no {device}/saw row to check against")
        for note in REFERENCE_NOTES:
            want = row.get(note)
            if want is None or want["value"] is None:
                continue
            y, f0_cmd = render(note)
            got = _report_read(mod, y, f0_cmd)
            d = abs(got - want["value"])
            worst = max(worst, d)
            checks.append(dict(device=device, note=note, frozen=want["value"],
                               reproduced=round(got, 3), delta_db=round(got - want["value"], 3)))
    if worst > REPRODUCTION_TOL_DB:
        raise Refused(
            f"the estimator reconstructed from {REPORT_COMMIT[:7]} does not reproduce "
            f"{REPORT_PATH}'s own ours/saw and ideal/saw rows (worst {worst:.2f} dB > "
            f"{REPRODUCTION_TOL_DB} dB). The frozen reference rows and anything measured "
            "today are then two different measurements and no margin between them is valid.")
    return dict(name="frozen_table_instrument_reproduces_its_own_rows", ok=True,
                commit=REPORT_COMMIT, worst_delta_db=round(worst, 3), rows=checks)


def assert_stale_json_refused() -> dict:
    """`docs/reference-voice-results.json` is the obvious machine-readable
    source and it is WRONG. It predates #87: git says it was last written by
    0929159 and the report by 74ce6a0, and its Surge rows still carry the flat
    "-60 dB at every pitch" that #87 traced to the harness adding a MIDI note
    per settle render. Quoting it would republish a withdrawn figure."""
    last = _git("log", "-1", "--format=%H", "--", STALE_JSON)
    if last and last.startswith(REPORT_COMMIT[:7]):
        # It was regenerated after all -- then the refusal is stale, not the file.
        raise Refused(f"{STALE_JSON} now postdates {REPORT_PATH}; this refusal needs "
                      "revisiting rather than trusting")
    return dict(name="stale_results_json_refused", ok=True, path=STALE_JSON,
                last_written_by=last[:7] if last else "<unknown>",
                report_written_by=REPORT_COMMIT[:7],
                reason="predates #87's corrected Surge waveform mapping; its surge rows "
                       "are the withdrawn flat -60 dB harness artefact")


# ---------------------------------------------------------------------------
# the frozen reference table
# ---------------------------------------------------------------------------
_SECTION = "3. ALIASING: inharmonic energy, dB of total, at rising pitch"
_HZ_TO_NOTE = {55: 33, 110: 45, 220: 57, 440: 69, 880: 81, 1760: 93}


def parse_report_table(path: pathlib.Path = None) -> dict:
    """Section 3 of `docs/reference-voice-report.txt`, as
    `{(device, wave): {note: {"value": dB|None, "at_floor": bool}}}`.

    `<` in a cell is the report's own mark for "within 3 dB of the ideal row at
    the same waveform and pitch", i.e. the estimator's floor rather than the
    instrument. It is carried through, not dropped: a margin computed from such
    a cell is a lower bound and is labelled one."""
    path = (ROOT / REPORT_PATH) if path is None else pathlib.Path(path)
    if not path.exists():
        raise Refused(f"the frozen reference table {path} is missing; nothing to compare against")
    lines = path.read_text().splitlines()
    try:
        start = next(i for i, ln in enumerate(lines) if _SECTION in ln)
    except StopIteration:
        raise Refused(f"{path} has no section {_SECTION!r}")
    header = None
    out: dict = {}
    for ln in lines[start + 1:]:
        if header is None:
            # The section title is followed by its own rule line; the column
            # header is the first line that names the pitches.
            if ln.startswith("device/wave"):
                header = [int(v) for v in ln.split()[1:]]
            continue
        if ln.startswith("  MARGIN") or ln.strip().startswith("===="):
            break
        m = re.match(r"^(\w+)/(\w+)\s+(.*)$", ln)
        if not m:
            continue
        device, wave, rest = m.group(1), m.group(2), m.group(3)
        cells = re.findall(r"(<?)\s*(-?\d+\.\d+|---)", rest)
        if len(cells) != len(header):
            continue
        row = {}
        for (mark, val), hz in zip(cells, header):
            note = _HZ_TO_NOTE.get(hz)
            if note is None:
                continue
            row[note] = dict(value=None if val == "---" else float(val),
                             at_floor=mark == "<")
        out[(device, wave)] = row
    if not out:
        raise Refused(f"parsed no rows out of section 3 of {path}")
    return out


def live_reference_table() -> dict:
    """--live-refs: re-render Surge XT and Mini V3 here. Refuses loudly on a
    host without the plugins rather than returning an empty table that would
    read as "no aliasing measured"."""
    try:
        import reference_rigs as rr                                 # noqa: F401
        import reference_voice as rv
    except Exception as e:                                          # pragma: no cover
        raise Refused(f"--live-refs: cannot import the rigs: {e}")
    missing = [p for p in (rr.PATH_SURGE, rr.PATH_MINIV3) if not os.path.exists(p)]
    if missing:                                                     # pragma: no cover
        raise Refused("--live-refs: these VST3 bundles are not on this host: "
                      + ", ".join(missing))
    out: dict = {}
    surge, mini = rr.SurgeRig("Type 2"), rr.MiniV3Rig()             # pragma: no cover
    try:                                                            # pragma: no cover
        for name, dev in (("surge", surge), ("miniv3", mini)):
            row = {}
            for note in REFERENCE_NOTES:
                f0 = vf.note_hz(note)
                r = rv.measure(dev.osc_tone("saw", note), f0, f"{name}/saw/{note}", "saw")
                row[note] = dict(value=r.get("inharmonic_db"), at_floor=False)
            out[(name, "saw")] = row
    finally:                                                        # pragma: no cover
        del surge, mini
    return out                                                      # pragma: no cover


# ---------------------------------------------------------------------------
# readings
# ---------------------------------------------------------------------------
def reading(y: np.ndarray, f0: float, what: str) -> dict:
    """One `inharmonic_fraction_db` reading, with its own measured floor beside
    it. `floor_limited` is the only honest answer when headroom is small: the
    number is then a property of the estimator, which is how this issue's whole
    55 Hz column came to be withdrawn."""
    est = am.inharmonic_fraction_db(y, f0, SR)
    if not est.ok:
        return dict(what=what, value=None, refused=est.reason)
    hd = float(est.detail["headroom_db"])
    return dict(what=what, value=round(float(est.value), 2),
                floor_db=round(float(est.detail["floor_db"]), 2),
                headroom_db=round(hd, 2), floor_limited=hd < MIN_HEADROOM_DB,
                window=est.detail["window"], refused=None)


def alias_curve_table() -> list:
    """Before and after at the six registers the locked test uses, plus the
    drop-decimator control that says the improvement is the FILTER and not the
    oversampling."""
    rows = []
    for note in ALIAS_NOTES:
        yb, f0 = render_base(note)
        ya, _ = render_2x(note)
        yd, _ = render_2x_drop(note)
        before = reading(yb, f0, "base rate")
        after = reading(ya, f0, "2x + FIR decimation")
        drop = reading(yd, f0, "2x + drop decimation (control)")
        rows.append(dict(
            note=note, f0_hz=round(f0, 2), before=before, after=after, control_drop=drop,
            improvement_db=None if before["value"] is None or after["value"] is None
            else round(before["value"] - after["value"], 2)))
    return rows


def reference_table(mod, frozen: dict) -> list:
    """The matched-pitch comparison, computed on ONE instrument.

    Both sides go through the frozen table's own estimator, because that is the
    only instrument the Surge and Mini V3 rows exist on. Ours is additionally
    read on today's Blackman-Harris estimator so the two can be seen not to
    disagree -- and, at 55 Hz, seen to disagree exactly where the old one is at
    its floor."""
    rows = []
    for note in REFERENCE_NOTES:
        f0_cmd = vf.note_hz(note)
        y2, f0_inc = render_2x(note)
        yb, _ = render_base(note)
        yi, _ = _ideal("saw", note)
        ours_2x_report = _report_read(mod, y2, f0_cmd)
        ours_base_report = _report_read(mod, yb, f0_cmd)
        ideal_report = _report_read(mod, yi, f0_cmd)
        today = reading(y2, f0_inc, "2x + FIR decimation (blackman-harris)")
        today_base = reading(yb, f0_inc, "base rate (blackman-harris)")
        # The report's own floor rule: within 3 dB of the ideal row is a limit.
        ours_at_floor = (ours_2x_report - ideal_report) < MIN_HEADROOM_DB
        row = dict(note=note, f0_hz=round(f0_cmd, 2),
                   ours_2x_report_db=round(ours_2x_report, 2),
                   ours_base_report_db=round(ours_base_report, 2),
                   ideal_report_db=round(ideal_report, 2),
                   ours_2x_headroom_over_ideal_db=round(ours_2x_report - ideal_report, 2),
                   ours_2x_floor_limited=ours_at_floor,
                   ours_2x_today=today, ours_base_today=today_base,
                   margins={})
        for device in ("surge", "miniv3"):
            cell = frozen.get((device, "saw"), {}).get(note)
            if cell is None or cell["value"] is None:
                row["margins"][device] = dict(reference_db=None, margin_db=None,
                                              kind="no qualified reference row")
                continue
            margin = ours_2x_report - cell["value"]
            if ours_at_floor or cell["at_floor"]:
                kind = "lower bound (a side of this margin is at the estimator's floor)"
            elif device == "miniv3":
                kind = ("lower bound (Mini V3's filter cannot be bypassed and can only "
                        "remove aliases)")
            else:
                kind = "value"
            row["margins"][device] = dict(reference_db=cell["value"],
                                          reference_at_floor=cell["at_floor"],
                                          margin_db=round(margin, 2), kind=kind)
        rows.append(row)
    return rows


# ---------------------------------------------------------------------------
# is the saw still the largest gap?
# ---------------------------------------------------------------------------
# The shapes this voice makes, in the frozen table's own names. `oversample_2x`
# covers `saw` only in the selected baseline: `fpga/SELECTED.md` carries
# OSC2X=1 with PULSE2X=0, so every other shape below is measured on the
# base-rate path, which is what it ships as.
SHAPES = ("saw", "square", "pulse25", "tri", "sine")


def shape_ranking(mod, frozen: dict) -> list:
    """Every waveform's gap to the references, so "the largest known voice
    defect" is re-derived rather than re-asserted after the saw moves.

    Each shape's own `ours/<wave>` row in the frozen table is reproduced here
    first. A shape whose row does not come back is reported as such and ranked
    nowhere -- the alternative is ranking a number this host cannot reproduce.
    The 55 Hz column is excluded from every aggregate: it was withdrawn for
    being the estimator's floor and nothing here revives it."""
    rows = []
    for wave in SHAPES:
        frozen_ours = frozen.get(("ours", wave), {})
        worst = {"surge": None, "miniv3": None, "ideal": None}
        repro = []
        for note in REFERENCE_NOTES:
            if note == 33:
                continue                       # the withdrawn floor-limited column
            f0_cmd = vf.note_hz(note)
            if wave == "sine":
                # `OscFx` has no sine; the voice's sine comes from the same
                # naive table, so render it the way reference_voice does.
                y = _ours_sine(note)
            else:
                y = vf.OscFx(wave, True).render(
                    int(SECONDS * SR), vf.phase_inc(vf.note_hz(note))).astype(np.float64) / FS
            got = _report_read(mod, y, f0_cmd)
            want = frozen_ours.get(note, {}).get("value")
            repro.append(dict(note=note, frozen=want, reproduced=round(got, 2),
                              delta_db=None if want is None else round(got - want, 2)))
            ideal = _report_read(mod, *_ideal(wave, note))
            if got - ideal < MIN_HEADROOM_DB:
                continue                       # ours is at the floor: no margin to take
            # ours-ideal first: the margin against a waveform with no aliasing
            # at all is the one that does not depend on a plugin's settings.
            if worst["ideal"] is None or got - ideal > worst["ideal"]["margin_db"]:
                worst["ideal"] = dict(note=note, f0_hz=round(f0_cmd, 1),
                                      margin_db=round(got - ideal, 2),
                                      ours_db=round(got, 2), reference_db=round(ideal, 2))
            for device in ("surge", "miniv3"):
                cell = frozen.get((device, wave), {}).get(note)
                if cell is None or cell["value"] is None or cell["at_floor"]:
                    continue
                m = got - cell["value"]
                if worst[device] is None or m > worst[device]["margin_db"]:
                    worst[device] = dict(note=note, f0_hz=round(f0_cmd, 1),
                                         margin_db=round(m, 2), ours_db=round(got, 2),
                                         reference_db=cell["value"])
        bad = [r for r in repro if r["delta_db"] is not None and abs(r["delta_db"]) > 1.0]
        rows.append(dict(wave=wave, path="base rate", worst=worst,
                         reproduces_frozen_ours_row=not bad, reproduction=repro))
    # ...and the saw once more, on the path that actually ships for it.
    worst = {"surge": None, "miniv3": None, "ideal": None}
    for note in REFERENCE_NOTES:
        if note == 33:
            continue
        f0_cmd = vf.note_hz(note)
        y2, _ = render_2x(note)
        got = _report_read(mod, y2, f0_cmd)
        ideal = _report_read(mod, *_ideal("saw", note))
        if got - ideal < MIN_HEADROOM_DB:
            continue
        if worst["ideal"] is None or got - ideal > worst["ideal"]["margin_db"]:
            worst["ideal"] = dict(note=note, f0_hz=round(f0_cmd, 1),
                                  margin_db=round(got - ideal, 2),
                                  ours_db=round(got, 2), reference_db=round(ideal, 2))
        for device in ("surge", "miniv3"):
            cell = frozen.get((device, "saw"), {}).get(note)
            if cell is None or cell["value"] is None or cell["at_floor"]:
                continue
            m = got - cell["value"]
            if worst[device] is None or m > worst[device]["margin_db"]:
                worst[device] = dict(note=note, f0_hz=round(f0_cmd, 1),
                                     margin_db=round(m, 2), ours_db=round(got, 2),
                                     reference_db=cell["value"])
    rows.append(dict(wave="saw", path="2x + FIR decimation (OSC2X=1, selected)",
                     worst=worst, reproduces_frozen_ours_row=None, reproduction=[]))
    return rows


def _ours_sine(note: int, n: int = None) -> np.ndarray:
    n = int(SECONDS * SR) if n is None else n
    inc = vf.phase_inc(vf.note_hz(note))
    ph = (np.arange(n, dtype=np.int64) * inc) & vf.PHASE_MASK
    return vf.naive_fx("sine", ph).astype(np.float64) / FS


_IDEAL_KIND = {"saw": ("saw", 0.5), "square": ("pulse", 0.5), "pulse25": ("pulse", 0.25),
               "tri": ("tri", 0.5), "sine": ("sine", 0.5)}


def _ideal(wave: str, note: int, n: int = None) -> tuple[np.ndarray, float]:
    """The alias-free closed form of `wave`, so the estimator's floor for this
    shape and pitch is measured rather than assumed. Same series as
    `reference_voice.ideal_tone`."""
    kind, duty = _IDEAL_KIND[wave]
    n = int(SECONDS * SR) if n is None else n
    f0 = vf.note_hz(note)
    t = np.arange(n) / SR
    y = np.zeros(n)
    k = 1
    while k * f0 < SR / 2:
        if kind == "saw":
            y += np.sin(2 * math.pi * k * f0 * t) / k
        elif kind == "tri":
            if k % 2:
                y += (-1) ** ((k - 1) // 2) * np.sin(2 * math.pi * k * f0 * t) / k ** 2
        elif kind == "sine":
            if k == 1:
                y += np.sin(2 * math.pi * f0 * t)
        else:
            y += math.sin(math.pi * k * duty) * np.cos(2 * math.pi * k * f0 * t) / k
        k += 1
    return y / max(np.abs(y).max(), 1e-12) * 0.5, f0


def verdict(alias_rows: list, ref_rows: list) -> dict:
    """The three questions issue #61's acceptance criteria ask, answered from
    the tables above rather than from a reading of them."""
    b0, b1 = alias_rows[0]["before"]["value"], alias_rows[-1]["before"]["value"]
    a0, a1 = alias_rows[0]["after"]["value"], alias_rows[-1]["after"]["value"]
    octaves = (ALIAS_NOTES[-1] - ALIAS_NOTES[0]) / 12.0
    usable = [r for r in ref_rows if not r["ours_2x_floor_limited"]]
    out = dict(
        before_slope_db_per_octave=round((b1 - b0) / octaves, 2),
        after_slope_db_per_octave=round((a1 - a0) / octaves, 2),
        improvement_db=dict(
            best=max(r["improvement_db"] for r in alias_rows),
            worst=min(r["improvement_db"] for r in alias_rows)),
        floor_limited_rows=[r["note"] for r in ref_rows if r["ours_2x_floor_limited"]])
    for device in ("surge", "miniv3"):
        ms = [r["margins"][device]["margin_db"] for r in usable
              if r["margins"][device]["margin_db"] is not None]
        out[f"gap_to_{device}_db"] = dict(min=min(ms), max=max(ms)) if ms else None
    return out


# ---------------------------------------------------------------------------
# report
# ---------------------------------------------------------------------------
def _fmt(v, w=8, nd=1):
    return " " * (w - 3) + "---" if v is None else f"{v:{w}.{nd}f}"


def format_report(res: dict) -> str:
    out = []
    p = res["provenance"]
    out.append("SAWTOOTH ALIASING AFTER THE 2x DECIMATION FILTER (issue #61)")
    out.append(f"  commit {p['commit'][:12]}{'  DIRTY TREE' if p['dirty'] else ''}"
               f"   {p['utc']}   {SECONDS} s at {SR} Hz")
    out.append("")
    out.append("PRECONDITIONS")
    for c in res["preconditions"]:
        out.append(f"  OK   {c['name']}")
    out.append("")
    out.append("1. OURS, BEFORE AND AFTER, at the six registers the locked test uses")
    out.append("   (no reference reading exists at these pitches; none is invented)")
    out.append(f"   {'note':>4} {'f0 Hz':>8} | {'before':>8} {'hr':>6} | {'after':>8} {'hr':>6}"
               f" | {'gain':>7} | {'drop ctl':>8} {'hr':>6}")
    for r in res["alias_curve"]:
        b, a, d = r["before"], r["after"], r["control_drop"]
        out.append(f"   {r['note']:4d} {r['f0_hz']:8.1f} | {_fmt(b['value'])} "
                   f"{_fmt(b.get('headroom_db'), 6)} | {_fmt(a['value'])} "
                   f"{_fmt(a.get('headroom_db'), 6)} | {_fmt(r['improvement_db'], 7)} | "
                   f"{_fmt(d['value'])} {_fmt(d.get('headroom_db'), 6)}")
    out.append("   'hr' is headroom over the estimator's own floor, MEASURED per call.")
    out.append("   'drop ctl' is the same 2x oscillator reduced by keeping the last")
    out.append("   sub-step (issue #80's defect). It must read WORSE than 'before'.")
    out.append("")
    out.append("2. MATCHED-PITCH COMPARISON against the frozen reference table")
    out.append(f"   {REPORT_PATH}, written by {REPORT_COMMIT[:7]} ({REPORT_DATE}),")
    out.append(f"   read with that commit's own Hann estimator on BOTH sides.")
    out.append(f"   {'note':>4} {'f0 Hz':>8} | {'ideal':>8} | {'ours base':>9} {'ours 2x':>8}"
               f" {'hr':>6} | {'surge':>8} {'mini':>8} | {'2x-surge':>8} {'2x-mini':>8}")
    for r in res["reference"]:
        ms, mm = r["margins"]["surge"], r["margins"]["miniv3"]
        out.append(f"   {r['note']:4d} {r['f0_hz']:8.1f} | {_fmt(r['ideal_report_db'])} | "
                   f"{_fmt(r['ours_base_report_db'], 9)} {_fmt(r['ours_2x_report_db'])} "
                   f"{_fmt(r['ours_2x_headroom_over_ideal_db'], 6)} | "
                   f"{_fmt(ms['reference_db'])} {_fmt(mm['reference_db'])} | "
                   f"{_fmt(ms['margin_db'])} {_fmt(mm['margin_db'])}")
    out.append("   positive = we carry MORE inharmonic energy than the reference.")
    out.append("   'hr' here is over the IDEAL row, which is that estimator's floor.")
    for r in res["reference"]:
        if r["ours_2x_floor_limited"]:
            out.append(f"   note {r['note']} ({r['f0_hz']:.0f} Hz): ours sits at the frozen "
                       "estimator's floor -- both margins are bounds, not values.")
    out.append("")
    out.append("3. THE SAME ROWS ON TODAY'S ESTIMATOR (blackman-harris, floor measured)")
    out.append(f"   {'note':>4} {'f0 Hz':>8} | {'ours base':>9} {'hr':>6} | {'ours 2x':>8} {'hr':>6}")
    for r in res["reference"]:
        b, a = r["ours_base_today"], r["ours_2x_today"]
        out.append(f"   {r['note']:4d} {r['f0_hz']:8.1f} | {_fmt(b['value'], 9)} "
                   f"{_fmt(b.get('headroom_db'), 6)} | {_fmt(a['value'])} "
                   f"{_fmt(a.get('headroom_db'), 6)}")
    out.append("   No reference row exists on this estimator, so no margin is printed here.")
    out.append("")
    out.append("4. IS THE SAW STILL THE LARGEST GAP?  worst margin over 110 Hz .. 1760 Hz")
    out.append("   (55 Hz excluded everywhere: that column was withdrawn as the estimator's floor)")
    out.append(f"   {'waveform':<10} {'path':<38} {'vs surge':>9} {'vs miniv3':>10} {'vs ideal':>9}")
    for r in res["shape_ranking"]:
        ws, wm, wi = r["worst"]["surge"], r["worst"]["miniv3"], r["worst"]["ideal"]
        out.append(f"   {r['wave']:<10} {r['path']:<38} "
                   f"{_fmt(None if ws is None else ws['margin_db'], 9)} "
                   f"{_fmt(None if wm is None else wm['margin_db'], 10)} "
                   f"{_fmt(None if wi is None else wi['margin_db'], 9)}")
    bad = [r["wave"] for r in res["shape_ranking"]
           if r["reproduces_frozen_ours_row"] is False]
    if bad:
        out.append("   NOT RANKED (this host does not reproduce the frozen ours row): "
                   + ", ".join(bad))
    out.append("   'vs ideal' is the margin against the alias-free closed form: the one")
    out.append("   column that does not depend on any plugin's settings being right.")
    out.append("   Only the saw takes the 2x chain in the selected baseline "
               "(fpga/SELECTED.md: OSC2X=1 PULSE2X=0).")
    out.append("")
    v = res["verdict"]
    out.append("VERDICT")
    out.append(f"  degradation with pitch: {v['before_slope_db_per_octave']:+.2f} dB/octave "
               f"before, {v['after_slope_db_per_octave']:+.2f} dB/octave after")
    out.append(f"  the filter buys {v['improvement_db']['worst']:.1f} .. "
               f"{v['improvement_db']['best']:.1f} dB across those six registers")
    for device in ("surge", "miniv3"):
        g = v[f"gap_to_{device}_db"]
        out.append(f"  gap to {device}: " + ("no usable row" if g is None else
                   f"{g['min']:+.1f} .. {g['max']:+.1f} dB (110 Hz up, matched pitch)"))
    if v["floor_limited_rows"]:
        out.append("  floor-limited and therefore not quoted: notes "
                   + ", ".join(str(n) for n in v["floor_limited_rows"]))
    return "\n".join(out)


# ---------------------------------------------------------------------------
def measure(live_refs: bool = False, argv=None) -> dict:
    checks = [assert_stale_json_refused(), assert_shipped_path()]
    frozen = parse_report_table()
    mod = load_report_estimator()
    checks.append(assert_report_instrument(mod, frozen))
    table = live_reference_table() if live_refs else frozen
    alias = alias_curve_table()
    ref = reference_table(mod, table)
    return dict(provenance=provenance(argv), preconditions=checks,
                reference_source=dict(
                    path=REPORT_PATH if not live_refs else "<live rigs>",
                    commit=REPORT_COMMIT if not live_refs else None,
                    date=REPORT_DATE if not live_refs else None,
                    estimator=("hann, as at " + REPORT_COMMIT[:7]) if not live_refs
                    else "blackman-harris (today)",
                    refused=[assert_stale_json_refused()["path"]]),
                alias_curve=alias, reference=ref,
                shape_ranking=shape_ranking(mod, frozen),
                verdict=verdict(alias, ref))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", help="write the JSON result here")
    ap.add_argument("--live-refs", action="store_true",
                    help="re-render Surge XT and Mini V3 (needs the VST3 bundles)")
    args = ap.parse_args(argv)
    try:
        res = measure(live_refs=args.live_refs, argv=sys.argv if argv is None else argv)
    except Refused as e:
        print(f"REFUSED: {e}", file=sys.stderr)
        return 2
    print(format_report(res))
    if args.out:
        pathlib.Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        pathlib.Path(args.out).write_text(json.dumps(res, indent=1, default=str) + "\n")
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
