#!/usr/bin/env python3
"""tools/r1_scorecard.py -- the R1 release view of the scorecard (#279,
plan087 section 10): five SEPARATE gates, never one averaged number.

    python tools/r1_scorecard.py            # writes docs/scorecard/r1/README.md
    python tools/r1_scorecard.py --check    # exit 1 if the committed view is stale

Inputs, all committed:
  fpga/release/r1-candidate.json          the frozen candidate (identity)
  fpga/reports/r1-candidate/summary.json  one row per qualification run, harvested
                                          from checked receipts (tools/r1_harvest.py)
  docs/scorecard/cases.csv + results/     the 100-case board (tools/scorecard.py)

Gate verdicts are derived here from those rows, not typed:
  trust           every required row has a valid receipt / record and every
                  declared control was caught
  implementation  the digital production-path rows (play, deadline, domain)
  playability     the live-MIDI rows; plus what is not yet exposed (#298)
  sound           a PROPERTY VECTOR per board case with its evidence level --
                  no pass fraction is presented as quality
  physical        BLOCKED: no R1 bitstream (#280), no capture (#208)
A gate with any row that is not PASS is not PASS. Missing rows are NO VERDICT.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import scorecard as sc                                   # noqa: E402

CANDIDATE = ROOT / "fpga/release/r1-candidate.json"
SUMMARY = ROOT / "fpga/reports/r1-candidate/summary.json"
OUT = ROOT / "docs/scorecard/r1/README.md"

GATES = ("trust", "implementation", "playability")
LEVEL = {"float-model": "float model", "fixed-model": "fixed-point model",
         "integrated-rtl": "integrated RTL (component bench)",
         "board-digital": "complete digital production path", "board-analog": "physical capture"}


def gate_verdict(rows: list) -> str:
    if not rows:
        return "NO VERDICT"
    vs = [r["verdict"] for r in rows]
    if "FAIL" in vs:
        return "FAIL"
    return "PASS" if all(v == "PASS" for v in vs) else "NO VERDICT"


def trust_rows(summary: dict) -> list:
    out = []
    for r in summary["runs"]:
        ok = r.get("receipt_valid", True) and all(r.get("controls", {}).values())
        out.append({"name": r["name"], "verdict": "PASS" if ok else "NO VERDICT",
                     "detail": f"receipt valid {r.get('receipt_valid')}; controls caught "
                               f"{sum(bool(v) for v in r.get('controls', {}).values())}/"
                               f"{len(r.get('controls', {}))}"})
    return out


def sound_rows() -> list:
    rows = []
    for case in sc.load_cases():
        res = sc.load_result(case["case_id"])
        if res is None:
            continue
        ev = sc.evaluate(case, res)
        props = ev.get("properties") or {}
        rows.append({"case": case["case_id"], "subject": case["subject"],
                     "state": ev["state"], "engine": ev.get("engine") or "",
                     "level": LEVEL.get(ev.get("engine") or "", "unknown"),
                     "commit": (res.get("source_commit") or "")[:8],
                     "props": {k: round(v, 2) for k, v in props.items()},
                     "why": ev.get("why", "")})
    return rows


def render(cand: dict, summary: dict) -> str:
    runs = summary["runs"]
    by_gate = {g: [r for r in runs if r["gate"] == g] for g in GATES}
    trust = trust_rows(summary)
    verdicts = {"trust": gate_verdict(trust),
                **{g: gate_verdict(by_gate[g]) for g in ("implementation", "playability")}}
    snd = sound_rows()
    n = {s: sum(1 for r in snd if r["state"] == s) for s in (sc.PASS, sc.FAIL, sc.NO_VERDICT)}
    total = len(sc.load_cases())
    L = []
    L.append("# R1 scorecard: five gates, no average\n")
    L.append("Generated by `tools/r1_scorecard.py` from `fpga/release/r1-candidate.json`, "
             "`fpga/reports/r1-candidate/summary.json` and the case board. Do not edit by hand; "
             "`--check` fails when this file is stale.\n")
    L.append(f"**Candidate:** {cand['candidate']}: contract revision {cand['contract_revision']}, "
             f"`{cand['rtl']['synth_design'].split(' -generic')[0]}` with "
             f"`OSC2X={cand['rtl']['configuration']['OSC2X']} FILTER2X="
             f"{cand['rtl']['configuration']['FILTER2X']} PULSE2X="
             f"{cand['rtl']['configuration']['PULSE2X']}`, RTL frozen at "
             f"`{cand['rtl']['frozen_at'][:12]}`, kit `{cand['kit']['sha256'][:12]}` "
             f"({cand['kit']['writes']} writes, clap ENV_FRATE[8] = "
             f"{cand['kit']['clap_final_strike']['value']}), host `{cand['host_image_selector']}`. "
             f"R0 is `{cand['r0_is']}`; nothing below is evidence about R0.\n")
    L.append(f"Evidence produced at `{summary['head'][:12]}` (origin/main "
             f"`{summary['origin_main'][:12]}`) on the build box.\n")
    L.append("| gate | question | verdict | evidence level |")
    L.append("|---|---|---|---|")
    L.append(f"| trust | are the results trustworthy? | **{verdicts['trust']}** | receipts re-checked; "
             "every declared control caught |")
    L.append(f"| implementation | does this implementation work? | **{verdicts['implementation']}** "
             "| RTL simulation of the Arty wrapper at its pins (digital production path, no image) |")
    L.append(f"| playability | is it an instrument? | **{verdicts['playability']}** (digital, "
             "11 of 16 sounds mapped) | live-MIDI session against the device contract and the RTL; "
             "no hardware latency |")
    L.append(f"| sound properties | does it meet its references? | **property vector** (below): "
             f"{n[sc.PASS]} pass, {n[sc.FAIL]} fail, {n[sc.NO_VERDICT]} no verdict, "
             f"{total - len(snd)} not run of {total} | mostly fixed-point model |")
    L.append("| physical | did the device produce it? | **BLOCKED** | no R1 bitstream (#280), no "
             "capture (#208); simulation cannot satisfy this gate |\n")
    for g in ("implementation", "playability"):
        L.append(f"## {g.capitalize()}\n")
        L.append("| run | identity (sender / target, kit) | workload | expected vs observed "
                 "coverage | verdict | evidence level |")
        L.append("|---|---|---|---|---|---|")
        for r in by_gate[g]:
            L.append(f"| {r['name']} | {r['identity']} | {r['workload']} | {r['coverage']} | "
                     f"**{r['verdict']}** | {r['level']} |")
        L.append("")
    if by_gate["playability"] is not None:
        L.append("The live player maps **11 of the 16** 808 sounds: BD, SD, LT, MT, HT, CH, OH, CP, "
                 "CB, CL and CY. The three congas, the rimshot and the maracas are refused as "
                 "unmapped; #298 tracks exposing them. MIDI-to-audio latency on hardware (USB/FTDI) "
                 "is not measured.\n")
    L.append("## Trust\n")
    L.append("| run | verdict | detail |")
    L.append("|---|---|---|")
    for r in trust:
        L.append(f"| {r['name']} | {r['verdict']} | {r['detail']} |")
    L.append("")
    L.append("## Sound properties (per case; distances are each property's error over its own "
             "tolerance, pass at <= 1)\n")
    L.append("None of these was measured on the R1 production path. Each row names its engine "
             "and the commit it was measured at; a fixed-point-model result supports R1 "
             "development and certifies neither R0 nor R1 playback.\n")
    L.append("| case | subject | state | properties | evidence level | measured at |")
    L.append("|---|---|---|---|---|---|")
    for r in snd:
        props = "; ".join(f"{k} {v}" for k, v in r["props"].items()) or r["why"]
        L.append(f"| {r['case']} | {r['subject']} | {r['state']} | {props} | {r['level']} | "
                 f"`{r['commit']}` |")
    L.append("")
    L.append("A count such as the pass total above is coverage, not a quality percentage or a "
             "release-readiness percentage.\n")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    for p in (CANDIDATE, SUMMARY):
        if not p.exists():
            print(f"r1_scorecard: REFUSED -- missing {p.relative_to(ROOT)}")
            return 2
    text = render(json.loads(CANDIDATE.read_text()), json.loads(SUMMARY.read_text()))
    if a.check:
        ok = OUT.exists() and OUT.read_text() == text
        print(f"r1_scorecard: {'current' if ok else 'STALE -- re-run tools/r1_scorecard.py'}")
        return 0 if ok else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"r1_scorecard: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
