#!/usr/bin/env python3
"""Known answers and controls for `tools/cymbal_tone_knob.py` (#369 step 9).

The instrument makes one claim -- that VR4's wiper position predicts the 808's
TONE law -- and the only way that claim is evidence rather than a fit is if the
apparatus can be shown to (a) recover a planted answer, (b) REJECT a planted
wrong one, and (c) refuse rather than answer when a precondition fails. Those
are the three groups below, in that order.

Nothing here needs the ~30 MB Fischer corpus except the tests that say so and
skip without it: the committed `fischer.json` carries the 25 measurements the
headline property runs on. Where `${GF180_REQUIRE_TR808_REFS}=1` those skips
become failures, `tools/test_run_case.py`'s convention exactly -- a required
gate that goes green through skips has checked nothing.
"""

from __future__ import annotations

import json
import math
import os
import pathlib
import sys

import numpy as np
import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "model"), str(ROOT / "tools")]
import cymbal_bands as cb                    # noqa: E402
import cymbal_tone_realisation as tr         # noqa: E402
import tone_stage_schematic as ts            # noqa: E402
import cymbal_tone_knob as tk                # noqa: E402


# ---------------------------------------------------------------------------
# the constants are the repository's, not this module's
# ---------------------------------------------------------------------------
def test_the_bounds_are_the_ones_the_repository_already_states():
    """A bound invented inside the module that uses it is a bound chosen to
    pass. Both of these live somewhere else and are asserted equal here so they
    cannot drift apart silently."""
    assert tk.BOUND_DB == tr.SHAPE_BOUND_DB
    assert tk.FLOOR_MARGIN_DB == cb.TRUNC_MARGIN_DB
    assert tk.WINDOWS["1s"] == (0.0, cb.ENERGY_S)


def test_the_codes_are_in_knob_order_not_filename_order():
    """`cymbal_bands.CODES` is ("00", "10", "25", "50", "75") -- FILENAME order,
    because "10" means 100 %. Reading a trend down that order puts TONE = full
    second and turns a falling quantity into a 109 % rise, which is exactly what
    the first version of `h-edt-falls-with-tone` reported (wrong-then-right 4).
    """
    assert tk.CODES == ("00", "25", "50", "75", "10")
    assert set(tk.CODES) == set(cb.CODES)
    assert [tk.FRAC[c] for c in tk.CODES] == [0.0, 0.25, 0.5, 0.75, 1.0]
    assert all(tk.FRAC[c] == cb.KNOB[c] / 10.0 for c in tk.CODES)


def test_the_pot_is_linear_and_both_ends_are_held_off_the_rail():
    assert tk.alpha_of(0.25) == pytest.approx(0.25)
    assert tk.alpha_of(0.75) == pytest.approx(0.75)
    assert 0.0 < tk.alpha_of(0.0) <= tk.ALPHA_EPS
    assert 1.0 - tk.ALPHA_EPS <= tk.alpha_of(1.0) < 1.0
    assert tk.alpha_of(0.25, mapping="inverted") == pytest.approx(0.75)


def test_the_tone_term_is_the_committed_module_s_own_network():
    """`tone_db` must reproduce `tone_stage_schematic`'s reported values at its
    own fitted wiper position. The same filter written twice, so the tolerance
    is transcription-level and not a fit tolerance."""
    cfg = tk.config()
    for band, want in tk.TONE_EXACT_DB.items():
        got = tk.tone_db(band, np.array(ts.CY_BANDS_HZ), ts.ALPHA_K1, cfg)
        assert got == pytest.approx(want, abs=tk.TONE_EXACT_TOL_DB), (band, got, want)


# ---------------------------------------------------------------------------
# (a) known answers: a planted balance and a planted law read back
# ---------------------------------------------------------------------------
def _synthetic(mapping, balance_db, *, cols=None):
    """H - L at every setting, generated BY the model at a known balance and a
    known alpha(TONE). Every DECAY column is given the same curve because the
    model has no DECAY dependence -- which is itself the point: the TONE law is
    structural, so a column-independent curve is what it predicts."""
    g = tk.gain_table(mapping=mapping)
    y = tk.predicted_hml(g, np.array([0.0, *balance_db]))
    return {d: {t: float(y[i]) for i, t in enumerate(tk.CODES)}
            for d in (cols or tk.CODES)}


@pytest.mark.parametrize("balance", [(10.0, 11.5), (0.0, 0.0), (-6.0, 18.0)])
def test_a_planted_balance_reads_back_from_its_own_curve(balance):
    """The fitter recovers a planted balance to the grid step, with a residual
    at the arithmetic's own noise. If this failed, every number the instrument
    reports would be a number about the fitter rather than about the machine."""
    meas = _synthetic("linear", balance)
    f = tk.fit_balance(tk.gain_table(mapping="linear"), meas)
    assert f["worst_db"] < 1e-6, f
    step = float(tk.BALANCE_DB[1] - tk.BALANCE_DB[0])
    assert f["balance_db"]["decay"] == pytest.approx(balance[0], abs=step)
    assert f["balance_db"]["short"] == pytest.approx(balance[1], abs=step)


def test_the_planted_curve_is_not_flat_so_the_recovery_is_not_vacuous():
    """A known answer that is constant is recovered by anything. The planted
    curve has to span more than the bound it is later judged against, or the
    test above proves only that 0 == 0."""
    meas = _synthetic("linear", (10.0, 11.5))
    span = max(meas["50"].values()) - min(meas["50"].values())
    assert span > 2 * tk.BOUND_DB, span


def test_a_planted_INVERTED_law_is_rejected_by_the_linear_fit():
    """The paired negative. Data generated by the inverted wiper law must MISS
    the bound when the linear law is fitted to it, with the same two free balance
    numbers available."""
    meas = _synthetic("inverted", (10.0, 11.5))
    f = tk.fit_balance(tk.gain_table(mapping="linear"), meas)
    assert f["worst_db"] > tk.BOUND_DB, f["worst_db"]


def test_the_family_CAN_reach_a_flat_curve_and_a_straight_ramp():
    """The uncomfortable half, pinned so it cannot quietly disappear.

    This test was written to fail -- "a flat TONE law must be rejected" -- and it
    did not: at a decay-dominated balance (+36/-30 dB) the same family predicts
    an H - L that barely moves across the whole wiper travel, and a straight ramp
    of the machine's own span is reachable too. So the headline residual is NOT
    on its own decisive, and the module's docstring says so because of this test.
    Wrong-then-right 6."""
    audit = tk.shape_audit(tk.from_artifact())
    assert audit["flat"]["reachable"], audit["flat"]
    assert audit["linear-ramp"]["reachable"], audit["linear-ramp"]
    # ... and the balance that does it is nowhere near the one the machine picks
    assert abs(audit["flat"]["balance_db"]["short"]
               - audit["machine"]["balance_db"]["short"]) > 20.0, audit


def test_the_family_cannot_reach_three_of_the_eight_stated_shapes():
    """The other side of the same measurement, and the one that makes the result
    evidence: reversing the machine's own curve, a step and a V are all out of
    reach of the same two free numbers."""
    audit = tk.shape_audit(tk.from_artifact())
    out = sorted(k for k, v in audit.items() if not v["reachable"])
    assert out == ["machine-reversed", "step", "vee"], audit
    assert audit["machine-reversed"]["worst_db"] > 5.0, audit["machine-reversed"]


# ---------------------------------------------------------------------------
# (b) the controls compose, and the blind ones are blind
# ---------------------------------------------------------------------------
def test_every_alternative_is_an_involution_of_the_configuration():
    """The alternatives are applied to whatever the defect left, so each must be
    its own inverse. This is the mechanism by which a defect is caught at all:
    under `ALPHA_INVERTED` the 'inverted' alternative has to become the TRUTH."""
    for alt in tk.ALTERNATIVES:
        base = tk.config()
        once = tk.config(alternative=alt)
        assert once != base, alt
        twice = tk.config(alternative=alt, mapping=once["mapping"])
        twice["rails"] = tk._swap(once["rails"],
                                  *{"low-on-top-rail": ("low", "short"),
                                    "ht2-ht3-swapped": ("decay", "short")}.get(alt, ("low", "low")))
        twice["tone_flat"] = (not once["tone_flat"]) if alt == "no-tone-network" else once["tone_flat"]
        assert twice["rails"] == base["rails"], alt
        assert twice["mapping"] == base["mapping"], alt
        assert twice["tone_flat"] == base["tone_flat"], alt


def test_config_rejects_a_name_it_does_not_know():
    with pytest.raises(ValueError):
        tk.config(defect="NOT_A_DEFECT")
    with pytest.raises(ValueError):
        tk.config(alternative="NOT_AN_ALTERNATIVE")


@pytest.mark.parametrize("defect", tk.DEFECTS)
def test_each_injected_defect_turns_at_least_one_named_property_red(defect):
    """Rule 2, per defect. The corpus-gated ones are in `CORPUS_DEFECTS` and are
    exercised by `test_the_corpus_gated_controls_fire` below."""
    clean = tk.properties()
    got = tk.properties(defect=defect)
    red = [n for n in tk.PROPERTIES if clean[n]["ok"] is True and got[n]["ok"] is not True]
    assert red, (defect, {n: (clean[n]["value"], got[n]["value"]) for n in tk.PROPERTIES})


_MEAS: dict = {}


def _maybe_measured():
    """The windowed measurement if the corpus is here, else None -- so the
    blindness assertions about the strike and tail windows are decided rather
    than skipped wherever the WAVs exist."""
    if "v" not in _MEAS:
        refs = tk.rc.configured_refs()
        _MEAS["v"] = (tk.measure_windows(refs) if (refs / "cy8").is_dir() else None)
    return _MEAS["v"]


@pytest.mark.parametrize("defect,blind", sorted(
    (d, p) for d, ps in tk.BLIND_PAIRS.items() for p in ps))
def test_each_asserted_blindness_is_verified_blind(defect, blind):
    """Rule 4's other half. `RAIL_SWAP_HT2_HT3` is the interesting row: it is
    visible to `tone-exact` and invisible to every alpha-law property, and that
    asymmetry is precisely why this instrument cannot resolve the assignment."""
    m = _maybe_measured()
    clean = tk.properties(meas=m)
    got = tk.properties(meas=(None if defect in tk.CORPUS_DEFECTS else m), defect=defect)
    if clean[blind]["ok"] is None:
        pytest.skip(f"{blind} is not decidable without the corpus")
    assert got[blind]["ok"] == clean[blind]["ok"], (defect, blind,
                                                    clean[blind]["value"], got[blind]["value"])


@pytest.mark.parametrize("blind", tk.BLIND_BY_CONSTRUCTION)
def test_the_globally_blind_control_moves_nothing(blind):
    clean, got = tk.properties(), tk.properties(defect=blind)
    moved = [n for n in tk.PROPERTIES
             if clean[n]["ok"] is not None and got[n]["ok"] != clean[n]["ok"]]
    assert not moved, (blind, moved)


def test_the_source_tilt_is_blind_and_by_how_much():
    """`SOURCE_FLAT` is asserted blind, so say what it is worth: step 8 found the
    source tilt moved an ABSOLUTE band energy by 4.6 dB, and it moves this
    RELATIVE quantity by hundredths. Both are true; the difference is the reason
    this is a control rather than an assumption."""
    a = tk.properties()["alpha-law-1s"]["value"]
    b = tk.properties(defect="SOURCE_FLAT")["alpha-law-1s"]["value"]
    assert abs(a - b) < 0.1, (a, b)


@pytest.fixture(scope="module")
def gate_without_corpus():
    """The no-corpus gate, run ONCE. `tk.check()` takes ~5 s, and the three
    tests below ask three different questions of the same run rather than
    paying for it three times."""
    return tk.check()


def test_the_gate_passes_on_this_tree_without_the_corpus(gate_without_corpus):
    """CLAUDE.md: run the gate against the current state before committing it.
    An unsatisfiable gate is worse than no gate."""
    ok, lines = gate_without_corpus
    assert ok, "\n".join(lines)


def test_the_two_corpus_gated_controls_are_NO_VERDICT_and_not_a_pass(gate_without_corpus):
    """Without the WAVs those two rows cannot be decided. Rule 5's condition 2:
    a mutant that does not execute is NO VERDICT, which is not a pass -- so the
    report must SAY so rather than omitting the row, which is the whole reason
    the flag below has to exist."""
    _, lines = gate_without_corpus
    for d in tk.CORPUS_DEFECTS:
        row = [ln for ln in lines if ln.startswith(d)]
        assert len(row) == 1, (d, lines)
        assert "NO VERDICT" in row[0], row[0]


def test_require_corpus_is_reachable_from_the_command_line(tmp_path, capsys):
    """The flag was documented in two places and `main` never read it, so the
    escalation the docs promised did not exist. Known answer: the same tree,
    the same absent corpus, TWO different exit codes -- 0 without the flag and
    1 with it. If argparse ever stops wiring it, this test is what goes red.

    And it must fail for the RIGHT reason: the two corpus-gated rows are what
    refuse, while every property decidable without the WAVs still passes in the
    same run. A gate that exits 1 because something else broke would satisfy
    the exit codes and teach a reader the opposite of the truth.
    """
    argv = ["--check", "--refs", str(tmp_path / "no-corpus-here")]
    assert tk.main(argv) == 0
    assert tk.main(argv + ["--require-corpus"]) == 1
    out = capsys.readouterr().out.splitlines()
    assert "REFUSED: --require-corpus" in "\n".join(out), out
    for d in tk.CORPUS_DEFECTS:
        assert any(ln.startswith(d) and "NO VERDICT" in ln and "REFUSED" in ln
                   for ln in out), (d, out)
    assert not [ln for ln in out if ln.rstrip().endswith("FAIL")], out


# ---------------------------------------------------------------------------
# (c) refusals -- a precondition that fails must not produce a number
# ---------------------------------------------------------------------------
def test_from_artifact_refuses_a_file_that_is_missing_a_setting(tmp_path):
    blob = json.loads(tk.FISCHER_JSON.read_text())
    del blob["CY2500"]
    p = tmp_path / "fischer.json"
    p.write_text(json.dumps(blob))
    with pytest.raises(tk.Refused, match="CY2500"):
        tk.from_artifact(p)


def test_from_artifact_refuses_a_setting_whose_measurement_refused(tmp_path):
    blob = json.loads(tk.FISCHER_JSON.read_text())
    blob["CY5025"]["H_minus_L_db"] = None
    p = tmp_path / "fischer.json"
    p.write_text(json.dumps(blob))
    with pytest.raises(tk.Refused, match="CY5025"):
        tk.from_artifact(p)


def test_from_artifact_refuses_an_absent_file(tmp_path):
    with pytest.raises(tk.Refused, match="absent"):
        tk.from_artifact(tmp_path / "nope.json")


def test_fit_balance_refuses_rather_than_dropping_a_refused_setting():
    """A window that refused one setting must not quietly become a 24-setting
    answer: the whole claim is "all 25"."""
    meas = _synthetic("linear", (10.0, 11.5))
    meas["25"]["75"] = None
    with pytest.raises(tk.Refused, match="CY7525"):
        tk.fit_balance(tk.gain_table(mapping="linear"), meas)


def test_the_floor_estimate_is_the_last_100ms_not_a_same_length_window():
    """Wrong-then-right 3, as a permanent control.

    A record 1.5 s long with a 1 s analysis window: the first version compared
    that window against the LAST 1 s of the same record, which on a real cymbal
    is still full of the tail, and reported a 14.7 dB "floor margin" for a
    recording whose floor is 66 dB down. Here the signal is a decaying tone with
    a genuinely tiny floor, and the two conventions are computed side by side.
    """
    sr = 44100
    t = np.arange(int(1.5 * sr)) / sr
    x = np.exp(-t / 0.15) * np.sin(2 * np.pi * 3450 * t) + 1e-4 * np.sin(2 * np.pi * 50 * t)
    sig, floor = tk._floorful_energy(x, sr, 0.0, 1.0)
    implemented = 10 * math.log10(sig / floor)
    same_length = 10 * math.log10(sig / float(np.sum(x[-sr:] ** 2)))
    assert implemented > 50.0, implemented
    assert same_length < 30.0, same_length
    assert implemented - same_length > 20.0, (implemented, same_length)


def test_a_window_that_does_not_fit_the_record_refuses():
    sr = 44100
    x = np.ones(int(0.4 * sr))
    with pytest.raises(tk.Refused, match="does not fit"):
        tk._floorful_energy(x, sr, 0.0, 1.0)


def test_a_record_too_short_to_carry_both_window_and_floor_refuses():
    sr = 44100
    x = np.ones(int(1.05 * sr))
    with pytest.raises(tk.Refused, match="floor estimate"):
        tk._floorful_energy(x, sr, 0.0, 1.0)


def test_balance_region_refuses_when_nothing_in_the_grid_reaches_the_bound():
    art = tk.from_artifact()
    with pytest.raises(tk.Refused, match="no balance"):
        tk.balance_region(tk.gain_table(mapping="inverted"), art, bound=0.5)


# ---------------------------------------------------------------------------
# the result, pinned so it cannot drift silently
# ---------------------------------------------------------------------------
def test_the_measured_span_is_large_enough_for_the_bound_to_discriminate():
    """A 3 dB bound on a quantity that only moves 1 dB would pass for any
    structure. Every column's TONE span must be at least twice the bound."""
    art = tk.from_artifact()
    for d in tk.CODES:
        span = max(art[d].values()) - min(art[d].values())
        assert span > 2 * tk.BOUND_DB, (d, span)


def test_the_linear_law_fits_and_the_three_alternatives_do_not():
    art = tk.from_artifact()
    head = tk.fit_balance(tk.gain_table(mapping="linear"), art)
    assert head["worst_db"] < 0.5, head["worst_db"]
    alts = tk.alternatives(art)
    for name in ("inverted", "no-tone-network", "low-on-top-rail"):
        assert alts[name]["worst_db"] > 4.0, (name, alts[name]["worst_db"])
    # and the one that is NOT excluded, stated rather than omitted
    assert alts["ht2-ht3-swapped"]["worst_db"] < tk.BOUND_DB


def test_the_linear_mapping_is_the_best_of_the_candidates_swept():
    sw = tk.mapping_sweep(tk.from_artifact())
    best = min(sw, key=lambda m: sw[m]["worst_db"])
    assert best == "linear", {m: v["worst_db"] for m, v in sw.items()}
    # ... and how much better, because "best" without a margin is not a result
    second = sorted(v["worst_db"] for v in sw.values())[1]
    assert second - sw["linear"]["worst_db"] < 0.5, sw["upper-half"]["worst_db"]


def test_the_balance_is_only_constrained_in_its_difference():
    """The honest form of "this measures the VCA drives": it does not. The
    admitted region fills the swept grid in both absolute weights."""
    r = tk.balance_region(tk.gain_table(mapping="linear"), tk.from_artifact())
    assert r["decay_db"] == [float(tk.BALANCE_DB[0]), float(tk.BALANCE_DB[-1])]
    assert r["short_db"] == [float(tk.BALANCE_DB[0]), float(tk.BALANCE_DB[-1])]
    lo, hi = r["short_minus_decay_db"]
    assert hi - lo < 20.0, r


# ---------------------------------------------------------------------------
# the four that need the corpus
# ---------------------------------------------------------------------------
def _refs_or_skip():
    """Optional locally, REQUIRED where ${GF180_REQUIRE_TR808_REFS}=1.

    `make reference-integration` sets it, and that target's whole contract is
    that a missing corpus REFUSES rather than skips -- an earlier version of
    this helper skipped unconditionally, so adding this file to that target
    would have added four tests that could go green having read nothing.
    """
    refs = tk.rc.configured_refs()
    if (refs / "cy8").is_dir():
        return refs
    msg = (f"the Fischer corpus is not present at {refs} (no cy8/); clone "
           f"tidalcycles/sounds-tr808-fischer there or set {tk.rc.REFS_ENV}")
    if os.environ.get(tk.rc.REFS_REQUIRED_ENV) == "1":
        pytest.fail(f"REFUSED: {msg}. {tk.rc.REFS_REQUIRED_ENV}=1 makes this a required "
                    f"gate, and a required gate does not pass by skipping.", pytrace=False)
    pytest.skip(f"OPTIONAL local run, skipped: {msg}")


@pytest.fixture(scope="module")
def measured():
    return tk.measure_windows(_refs_or_skip())


def test_the_1s_window_reproduces_the_committed_artifact(measured):
    """The binding that makes the other two windows statements about the same
    recordings the qualified instrument already measured."""
    art = tk.from_artifact()
    for d in tk.CODES:
        for t in tk.CODES:
            assert measured["hml"]["1s"][d][t] == pytest.approx(art[d][t], abs=0.01), (t, d)


def test_all_three_windows_clear_the_floor_at_every_setting(measured):
    assert measured["n_refused"] == 0
    assert measured["min_floor_margin_db"] > tk.FLOOR_MARGIN_DB, measured["min_floor_margin_db"]


def test_the_law_holds_in_the_two_windows_the_artifact_does_not_carry(measured):
    g = tk.gain_table(mapping="linear")
    for w in ("strike", "tail"):
        f = tk.fit_balance(g, measured["hml"][w])
        assert f["worst_db"] <= tk.BOUND_DB, (w, f["worst_db"])


def test_the_corpus_gated_controls_fire(measured):
    """`WRONG_ANALYSIS_BANDS` and `SHORT_RECORD` can only be judged where the
    WAVs are, so they are NO VERDICT in CI and asserted here."""
    clean = tk.properties(meas=measured)
    for defect in tk.CORPUS_DEFECTS:
        got = tk.properties(defect=defect)
        red = [n for n in tk.PROPERTIES
               if clean[n]["ok"] is True and got[n]["ok"] is not True]
        assert red, defect


def test_the_required_corpus_gate_is_satisfiable_where_the_wavs_are():
    """The other half of the flag above, and the one that has to be run before
    the Makefile target quoting it is committed: with the corpus present,
    `--check --require-corpus` must EXIT 0. An unsatisfiable gate is worse than
    no gate, so this is the test that would have caught one."""
    refs = _refs_or_skip()
    assert tk.main(["--check", "--require-corpus", "--refs", str(refs)]) == 0
